using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using Avalonia;
using Avalonia.Controls;
using Avalonia.Controls.Primitives;
using Avalonia.Input;
using Avalonia.Interactivity;
using Avalonia.Layout;
using Avalonia.Markup.Xaml;
using Avalonia.Markup.Xaml.XamlIl.Runtime;
using Avalonia.Media;
using Avalonia.Media.Immutable;
using CompiledAvaloniaXaml;

namespace Pfm.Views;

public class HelpWindow : Window
{
	private int _selectedTabIndex;

	[GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.1.0.0")]
	internal Button TabBtn0;

	[GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.1.0.0")]
	internal Button TabBtn1;

	[GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.1.0.0")]
	internal Button TabBtn2;

	[GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.1.0.0")]
	internal Button TabBtn3;

	[GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.1.0.0")]
	internal ScrollViewer TabContent0;

	[GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.1.0.0")]
	internal ScrollViewer TabContent1;

	[GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.1.0.0")]
	internal ScrollViewer TabContent2;

	[GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.1.0.0")]
	internal ScrollViewer TabContent3;

	[CompilerGenerated]
	private static Action<object> _0021XamlIlPopulateOverride;

	public HelpWindow()
	{
		InitializeComponent();
		ShowTab(0);
	}

	private void OnTitleBarPointerPressed(object? sender, PointerPressedEventArgs args)
	{
		if (args.GetCurrentPoint(sender as Control).Properties.IsLeftButtonPressed)
		{
			BeginMoveDrag(args);
		}
	}

	private void OnMinimizeClick(object? sender, RoutedEventArgs args)
	{
		base.WindowState = WindowState.Minimized;
	}

	private void OnCloseClick(object? sender, RoutedEventArgs args)
	{
		Close();
	}

	private void ShowTab(int index)
	{
		_selectedTabIndex = index;
		ScrollViewer scrollViewer = this.FindControl<ScrollViewer>("TabContent0");
		ScrollViewer scrollViewer2 = this.FindControl<ScrollViewer>("TabContent1");
		ScrollViewer scrollViewer3 = this.FindControl<ScrollViewer>("TabContent2");
		ScrollViewer scrollViewer4 = this.FindControl<ScrollViewer>("TabContent3");
		if (scrollViewer != null)
		{
			scrollViewer.IsVisible = index == 0;
		}
		if (scrollViewer2 != null)
		{
			scrollViewer2.IsVisible = index == 1;
		}
		if (scrollViewer3 != null)
		{
			scrollViewer3.IsVisible = index == 2;
		}
		if (scrollViewer4 != null)
		{
			scrollViewer4.IsVisible = index == 3;
		}
		Button button = this.FindControl<Button>("TabBtn0");
		Button button2 = this.FindControl<Button>("TabBtn1");
		Button button3 = this.FindControl<Button>("TabBtn2");
		Button button4 = this.FindControl<Button>("TabBtn3");
		button?.Classes.Set("tab-active", index == 0);
		button2?.Classes.Set("tab-active", index == 1);
		button3?.Classes.Set("tab-active", index == 2);
		button4?.Classes.Set("tab-active", index == 3);
	}

	private void OnTabWorkflowClick(object? sender, RoutedEventArgs args)
	{
		ShowTab(0);
	}

	private void OnTabClassesClick(object? sender, RoutedEventArgs args)
	{
		ShowTab(1);
	}

	private void OnTabVariablesClick(object? sender, RoutedEventArgs args)
	{
		ShowTab(2);
	}

	private void OnTabExamplesClick(object? sender, RoutedEventArgs args)
	{
		ShowTab(3);
	}

	[GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.1.0.0")]
	[ExcludeFromCodeCoverage]
	public void InitializeComponent(bool loadXaml = true)
	{
		if (loadXaml)
		{
			_0021XamlIlPopulateTrampoline(this);
		}
		INameScope nameScope = this.FindNameScope();
		TabBtn0 = nameScope?.Find<Button>("TabBtn0");
		TabBtn1 = nameScope?.Find<Button>("TabBtn1");
		TabBtn2 = nameScope?.Find<Button>("TabBtn2");
		TabBtn3 = nameScope?.Find<Button>("TabBtn3");
		TabContent0 = nameScope?.Find<ScrollViewer>("TabContent0");
		TabContent1 = nameScope?.Find<ScrollViewer>("TabContent1");
		TabContent2 = nameScope?.Find<ScrollViewer>("TabContent2");
		TabContent3 = nameScope?.Find<ScrollViewer>("TabContent3");
	}

	[CompilerGenerated]
	private static void _0021XamlIlPopulate(IServiceProvider P_0, HelpWindow P_1)
	{
		CompiledAvaloniaXaml.XamlIlContext.Context<HelpWindow> context = new CompiledAvaloniaXaml.XamlIlContext.Context<HelpWindow>(P_0, new object[1] { _0021AvaloniaResources.NamespaceInfo_003A_002FViews_002FHelpWindow_002Eaxaml.Singleton }, "avares://PFMS/Views/HelpWindow.axaml")
		{
			RootObject = P_1,
			IntermediateRoot = P_1
		};
		((ISupportInitialize)P_1).BeginInit();
		P_1.Title = "PFMS Help";
		P_1.Width = 820.0;
		P_1.Height = 680.0;
		P_1.MinWidth = 680.0;
		P_1.MinHeight = 520.0;
		P_1.WindowDecorations = WindowDecorations.None;
		P_1.CanResize = true;
		P_1.Background = new ImmutableSolidColorBrush(16777215u);
		P_1.TransparencyLevelHint = new WindowTransparencyLevel[2]
		{
			WindowTransparencyLevel.AcrylicBlur,
			WindowTransparencyLevel.Blur
		};
		Border border2;
		Border border = (border2 = new Border());
		((ISupportInitialize)border).BeginInit();
		P_1.Content = border;
		border2.Classes.Add("glass-shell");
		border2.CornerRadius = new CornerRadius(8.0, 8.0, 8.0, 8.0);
		border2.Padding = new Thickness(12.0, 12.0, 12.0, 12.0);
		Grid grid2;
		Grid grid = (grid2 = new Grid());
		((ISupportInitialize)grid).BeginInit();
		border2.Child = grid;
		RowDefinitions rowDefinitions = new RowDefinitions();
		rowDefinitions.Capacity = 3;
		rowDefinitions.Add(new RowDefinition(new GridLength(38.0, GridUnitType.Pixel)));
		rowDefinitions.Add(new RowDefinition(new GridLength(0.0, GridUnitType.Auto)));
		rowDefinitions.Add(new RowDefinition(new GridLength(1.0, GridUnitType.Star)));
		grid2.RowDefinitions = rowDefinitions;
		Controls children = grid2.Children;
		Grid grid4;
		Grid grid3 = (grid4 = new Grid());
		((ISupportInitialize)grid3).BeginInit();
		children.Add(grid3);
		grid4.AddHandler(InputElement.PointerPressedEvent, context.RootObject.OnTitleBarPointerPressed);
		Controls children2 = grid4.Children;
		TextBlock textBlock2;
		TextBlock textBlock = (textBlock2 = new TextBlock());
		((ISupportInitialize)textBlock).BeginInit();
		children2.Add(textBlock);
		textBlock2.Text = "PFMS Help";
		textBlock2.Margin = new Thickness(12.0, 0.0, 0.0, 0.0);
		textBlock2.VerticalAlignment = VerticalAlignment.Center;
		textBlock2.FontWeight = FontWeight.DemiBold;
		textBlock2.FontSize = 14.0;
		((ISupportInitialize)textBlock2).EndInit();
		Controls children3 = grid4.Children;
		StackPanel stackPanel2;
		StackPanel stackPanel = (stackPanel2 = new StackPanel());
		((ISupportInitialize)stackPanel).BeginInit();
		children3.Add(stackPanel);
		stackPanel2.HorizontalAlignment = HorizontalAlignment.Right;
		stackPanel2.Orientation = Orientation.Horizontal;
		Controls children4 = stackPanel2.Children;
		Button button2;
		Button button = (button2 = new Button());
		((ISupportInitialize)button).BeginInit();
		children4.Add(button);
		button2.Classes.Add("title-bar-btn");
		button2.Content = "_";
		button2.AddHandler((RoutedEvent)Button.ClickEvent, (Delegate)new EventHandler<RoutedEventArgs>(context.RootObject.OnMinimizeClick), RoutingStrategies.Direct | RoutingStrategies.Bubble, false);
		((ISupportInitialize)button2).EndInit();
		Controls children5 = stackPanel2.Children;
		Button button5;
		Button button4 = (button5 = new Button());
		((ISupportInitialize)button4).BeginInit();
		children5.Add(button4);
		button5.Classes.Add("title-bar-btn");
		button5.Classes.Add("close");
		button5.Content = "X";
		button5.AddHandler((RoutedEvent)Button.ClickEvent, (Delegate)new EventHandler<RoutedEventArgs>(context.RootObject.OnCloseClick), RoutingStrategies.Direct | RoutingStrategies.Bubble, false);
		((ISupportInitialize)button5).EndInit();
		((ISupportInitialize)stackPanel2).EndInit();
		((ISupportInitialize)grid4).EndInit();
		Controls children6 = grid2.Children;
		StackPanel stackPanel4;
		StackPanel stackPanel3 = (stackPanel4 = new StackPanel());
		((ISupportInitialize)stackPanel3).BeginInit();
		children6.Add(stackPanel3);
		Grid.SetRow(stackPanel4, 1);
		stackPanel4.Margin = new Thickness(8.0, 4.0, 8.0, 0.0);
		stackPanel4.Orientation = Orientation.Horizontal;
		Controls children7 = stackPanel4.Children;
		Button button7;
		Button button6 = (button7 = new Button());
		((ISupportInitialize)button6).BeginInit();
		children7.Add(button6);
		button7.Name = "TabBtn0";
		object element = button7;
		context.AvaloniaNameScope.Register("TabBtn0", element);
		button7.Content = "Workflow";
		button7.Classes.Add("tab-btn");
		button7.Classes.Add("tab-active");
		button7.AddHandler((RoutedEvent)Button.ClickEvent, (Delegate)new EventHandler<RoutedEventArgs>(context.RootObject.OnTabWorkflowClick), RoutingStrategies.Direct | RoutingStrategies.Bubble, false);
		((ISupportInitialize)button7).EndInit();
		Controls children8 = stackPanel4.Children;
		Button button9;
		Button button8 = (button9 = new Button());
		((ISupportInitialize)button8).BeginInit();
		children8.Add(button8);
		button9.Name = "TabBtn1";
		element = button9;
		context.AvaloniaNameScope.Register("TabBtn1", element);
		button9.Content = "Classes";
		button9.Classes.Add("tab-btn");
		button9.AddHandler((RoutedEvent)Button.ClickEvent, (Delegate)new EventHandler<RoutedEventArgs>(context.RootObject.OnTabClassesClick), RoutingStrategies.Direct | RoutingStrategies.Bubble, false);
		((ISupportInitialize)button9).EndInit();
		Controls children9 = stackPanel4.Children;
		Button button11;
		Button button10 = (button11 = new Button());
		((ISupportInitialize)button10).BeginInit();
		children9.Add(button10);
		button11.Name = "TabBtn2";
		element = button11;
		context.AvaloniaNameScope.Register("TabBtn2", element);
		button11.Content = "Variables";
		button11.Classes.Add("tab-btn");
		button11.AddHandler((RoutedEvent)Button.ClickEvent, (Delegate)new EventHandler<RoutedEventArgs>(context.RootObject.OnTabVariablesClick), RoutingStrategies.Direct | RoutingStrategies.Bubble, false);
		((ISupportInitialize)button11).EndInit();
		Controls children10 = stackPanel4.Children;
		Button button13;
		Button button12 = (button13 = new Button());
		((ISupportInitialize)button12).BeginInit();
		children10.Add(button12);
		button13.Name = "TabBtn3";
		element = button13;
		context.AvaloniaNameScope.Register("TabBtn3", element);
		button13.Content = "Examples";
		button13.Classes.Add("tab-btn");
		button13.AddHandler((RoutedEvent)Button.ClickEvent, (Delegate)new EventHandler<RoutedEventArgs>(context.RootObject.OnTabExamplesClick), RoutingStrategies.Direct | RoutingStrategies.Bubble, false);
		((ISupportInitialize)button13).EndInit();
		((ISupportInitialize)stackPanel4).EndInit();
		Controls children11 = grid2.Children;
		ScrollViewer scrollViewer2;
		ScrollViewer scrollViewer = (scrollViewer2 = new ScrollViewer());
		((ISupportInitialize)scrollViewer).BeginInit();
		children11.Add(scrollViewer);
		scrollViewer2.Name = "TabContent0";
		element = scrollViewer2;
		context.AvaloniaNameScope.Register("TabContent0", element);
		Grid.SetRow(scrollViewer2, 2);
		scrollViewer2.Margin = new Thickness(8.0, 4.0, 8.0, 8.0);
		scrollViewer2.VerticalScrollBarVisibility = ScrollBarVisibility.Auto;
		StackPanel stackPanel6;
		StackPanel stackPanel5 = (stackPanel6 = new StackPanel());
		((ISupportInitialize)stackPanel5).BeginInit();
		scrollViewer2.Content = stackPanel5;
		stackPanel6.Spacing = 18.0;
		Controls children12 = stackPanel6.Children;
		StackPanel stackPanel8;
		StackPanel stackPanel7 = (stackPanel8 = new StackPanel());
		((ISupportInitialize)stackPanel7).BeginInit();
		children12.Add(stackPanel7);
		stackPanel8.Spacing = 5.0;
		Controls children13 = stackPanel8.Children;
		TextBlock textBlock4;
		TextBlock textBlock3 = (textBlock4 = new TextBlock());
		((ISupportInitialize)textBlock3).BeginInit();
		children13.Add(textBlock3);
		textBlock4.Text = "Pablos Fishing Macro Studio";
		textBlock4.Classes.Add("page-title");
		((ISupportInitialize)textBlock4).EndInit();
		Controls children14 = stackPanel8.Children;
		TextBlock textBlock6;
		TextBlock textBlock5 = (textBlock6 = new TextBlock());
		((ISupportInitialize)textBlock5).BeginInit();
		children14.Add(textBlock5);
		textBlock6.Text = "F6 starts the enabled configuration, F7 stops it. Powered by YOLO object detection.";
		textBlock6.Classes.Add("page-subtitle");
		textBlock6.TextWrapping = TextWrapping.Wrap;
		((ISupportInitialize)textBlock6).EndInit();
		((ISupportInitialize)stackPanel8).EndInit();
		Controls children15 = stackPanel6.Children;
		StackPanel stackPanel10;
		StackPanel stackPanel9 = (stackPanel10 = new StackPanel());
		((ISupportInitialize)stackPanel9).BeginInit();
		children15.Add(stackPanel9);
		stackPanel10.Spacing = 8.0;
		Controls children16 = stackPanel10.Children;
		TextBlock textBlock8;
		TextBlock textBlock7 = (textBlock8 = new TextBlock());
		((ISupportInitialize)textBlock7).BeginInit();
		children16.Add(textBlock7);
		textBlock8.Text = "Runtime phases";
		textBlock8.Classes.Add("section-title");
		((ISupportInitialize)textBlock8).EndInit();
		Controls children17 = stackPanel10.Children;
		TextBlock textBlock10;
		TextBlock textBlock9 = (textBlock10 = new TextBlock());
		((ISupportInitialize)textBlock9).BeginInit();
		children17.Add(textBlock9);
		textBlock10.Text = "1. Cast: PFMS moves the cursor to the capture area center and holds left mouse button for Cast hold ms.";
		textBlock10.Classes.Add("banner-copy");
		textBlock10.TextWrapping = TextWrapping.Wrap;
		((ISupportInitialize)textBlock10).EndInit();
		Controls children18 = stackPanel10.Children;
		TextBlock textBlock12;
		TextBlock textBlock11 = (textBlock12 = new TextBlock());
		((ISupportInitialize)textBlock11).BeginInit();
		children18.Add(textBlock11);
		textBlock12.Text = "2. Shake: PFMS spams the configured shake key each frame while waiting for YOLO to detect both Pursue and Control classes.";
		textBlock12.Classes.Add("banner-copy");
		textBlock12.TextWrapping = TextWrapping.Wrap;
		((ISupportInitialize)textBlock12).EndInit();
		Controls children19 = stackPanel10.Children;
		TextBlock textBlock14;
		TextBlock textBlock13 = (textBlock14 = new TextBlock());
		((ISupportInitialize)textBlock13).BeginInit();
		children19.Add(textBlock13);
		textBlock14.Text = "3. Fish: PFMS blends all detected Pursue and Avoid boxes into a target position. The bar is held or released using Kp, Kd, and dead-zone settings.";
		textBlock14.Classes.Add("banner-copy");
		textBlock14.TextWrapping = TextWrapping.Wrap;
		((ISupportInitialize)textBlock14).EndInit();
		Controls children20 = stackPanel10.Children;
		TextBlock textBlock16;
		TextBlock textBlock15 = (textBlock16 = new TextBlock());
		((ISupportInitialize)textBlock15).BeginInit();
		children20.Add(textBlock15);
		textBlock16.Text = "4. Recast: if all required boxes disappear for 500 ms, or only one partial element remains for 5 seconds, PFMS recasts.";
		textBlock16.Classes.Add("banner-copy");
		textBlock16.TextWrapping = TextWrapping.Wrap;
		((ISupportInitialize)textBlock16).EndInit();
		((ISupportInitialize)stackPanel10).EndInit();
		Controls children21 = stackPanel6.Children;
		StackPanel stackPanel12;
		StackPanel stackPanel11 = (stackPanel12 = new StackPanel());
		((ISupportInitialize)stackPanel11).BeginInit();
		children21.Add(stackPanel11);
		stackPanel12.Spacing = 8.0;
		Controls children22 = stackPanel12.Children;
		TextBlock textBlock18;
		TextBlock textBlock17 = (textBlock18 = new TextBlock());
		((ISupportInitialize)textBlock17).BeginInit();
		children22.Add(textBlock17);
		textBlock18.Text = "Settings";
		textBlock18.Classes.Add("section-title");
		((ISupportInitialize)textBlock18).EndInit();
		Controls children23 = stackPanel12.Children;
		TextBlock textBlock20;
		TextBlock textBlock19 = (textBlock20 = new TextBlock());
		((ISupportInitialize)textBlock19).BeginInit();
		children23.Add(textBlock19);
		textBlock20.Text = "Start/Stop hotkeys (F1-F12) and the game overlay toggle are in the Settings page. The overlay shows live detection boxes over your game.";
		textBlock20.Classes.Add("banner-copy");
		textBlock20.TextWrapping = TextWrapping.Wrap;
		((ISupportInitialize)textBlock20).EndInit();
		Controls children24 = stackPanel12.Children;
		TextBlock textBlock22;
		TextBlock textBlock21 = (textBlock22 = new TextBlock());
		((ISupportInitialize)textBlock21).BeginInit();
		children24.Add(textBlock21);
		textBlock22.Text = "Configurations are stored at %APPDATA%\\Pfm\\configurations.json.";
		textBlock22.Classes.Add("path-label");
		((ISupportInitialize)textBlock22).EndInit();
		((ISupportInitialize)stackPanel12).EndInit();
		((ISupportInitialize)stackPanel6).EndInit();
		((ISupportInitialize)scrollViewer2).EndInit();
		Controls children25 = grid2.Children;
		ScrollViewer scrollViewer4;
		ScrollViewer scrollViewer3 = (scrollViewer4 = new ScrollViewer());
		((ISupportInitialize)scrollViewer3).BeginInit();
		children25.Add(scrollViewer3);
		scrollViewer4.Name = "TabContent1";
		element = scrollViewer4;
		context.AvaloniaNameScope.Register("TabContent1", element);
		Grid.SetRow(scrollViewer4, 2);
		scrollViewer4.Margin = new Thickness(8.0, 4.0, 8.0, 8.0);
		scrollViewer4.VerticalScrollBarVisibility = ScrollBarVisibility.Auto;
		scrollViewer4.IsVisible = false;
		StackPanel stackPanel14;
		StackPanel stackPanel13 = (stackPanel14 = new StackPanel());
		((ISupportInitialize)stackPanel13).BeginInit();
		scrollViewer4.Content = stackPanel13;
		stackPanel14.Spacing = 14.0;
		Controls children26 = stackPanel14.Children;
		StackPanel stackPanel16;
		StackPanel stackPanel15 = (stackPanel16 = new StackPanel());
		((ISupportInitialize)stackPanel15).BeginInit();
		children26.Add(stackPanel15);
		stackPanel16.Spacing = 5.0;
		Controls children27 = stackPanel16.Children;
		TextBlock textBlock24;
		TextBlock textBlock23 = (textBlock24 = new TextBlock());
		((ISupportInitialize)textBlock23).BeginInit();
		children27.Add(textBlock23);
		textBlock24.Text = "Class behaviors";
		textBlock24.Classes.Add("page-title");
		((ISupportInitialize)textBlock24).EndInit();
		Controls children28 = stackPanel16.Children;
		TextBlock textBlock26;
		TextBlock textBlock25 = (textBlock26 = new TextBlock());
		((ISupportInitialize)textBlock25).BeginInit();
		children28.Add(textBlock25);
		textBlock26.Text = "Every class in the model class table must have a behavior. One Control and at least one Pursue are required.";
		textBlock26.Classes.Add("page-subtitle");
		textBlock26.TextWrapping = TextWrapping.Wrap;
		((ISupportInitialize)textBlock26).EndInit();
		((ISupportInitialize)stackPanel16).EndInit();
		Controls children29 = stackPanel14.Children;
		Border border4;
		Border border3 = (border4 = new Border());
		((ISupportInitialize)border3).BeginInit();
		children29.Add(border3);
		border4.Classes.Add("feature-card");
		border4.Padding = new Thickness(16.0, 16.0, 16.0, 16.0);
		Grid grid7;
		Grid grid6 = (grid7 = new Grid());
		((ISupportInitialize)grid6).BeginInit();
		border4.Child = grid6;
		RowDefinitions rowDefinitions2 = new RowDefinitions();
		rowDefinitions2.Capacity = 5;
		rowDefinitions2.Add(new RowDefinition(new GridLength(0.0, GridUnitType.Auto)));
		rowDefinitions2.Add(new RowDefinition(new GridLength(0.0, GridUnitType.Auto)));
		rowDefinitions2.Add(new RowDefinition(new GridLength(0.0, GridUnitType.Auto)));
		rowDefinitions2.Add(new RowDefinition(new GridLength(0.0, GridUnitType.Auto)));
		rowDefinitions2.Add(new RowDefinition(new GridLength(0.0, GridUnitType.Auto)));
		grid7.RowDefinitions = rowDefinitions2;
		ColumnDefinitions columnDefinitions = new ColumnDefinitions();
		columnDefinitions.Capacity = 2;
		columnDefinitions.Add(new ColumnDefinition(new GridLength(100.0, GridUnitType.Pixel)));
		columnDefinitions.Add(new ColumnDefinition(new GridLength(1.0, GridUnitType.Star)));
		grid7.ColumnDefinitions = columnDefinitions;
		grid7.RowSpacing = 10.0;
		grid7.ColumnSpacing = 14.0;
		Controls children30 = grid7.Children;
		TextBlock textBlock28;
		TextBlock textBlock27 = (textBlock28 = new TextBlock());
		((ISupportInitialize)textBlock27).BeginInit();
		children30.Add(textBlock27);
		textBlock28.Text = "Control";
		textBlock28.Classes.Add("mechanic-badge");
		textBlock28.VerticalAlignment = VerticalAlignment.Top;
		((ISupportInitialize)textBlock28).EndInit();
		Controls children31 = grid7.Children;
		TextBlock textBlock30;
		TextBlock textBlock29 = (textBlock30 = new TextBlock());
		((ISupportInitialize)textBlock29).BeginInit();
		children31.Add(textBlock29);
		Grid.SetColumn(textBlock30, 1);
		textBlock30.Text = "Marks the player bar. Exactly one class must have this behavior. The bar's center X is used as the reference point for all steering.";
		textBlock30.Classes.Add("banner-copy");
		textBlock30.TextWrapping = TextWrapping.Wrap;
		((ISupportInitialize)textBlock30).EndInit();
		Controls children32 = grid7.Children;
		TextBlock textBlock32;
		TextBlock textBlock31 = (textBlock32 = new TextBlock());
		((ISupportInitialize)textBlock31).BeginInit();
		children32.Add(textBlock31);
		Grid.SetRow(textBlock32, 1);
		textBlock32.Text = "Pursue";
		textBlock32.Classes.Add("mechanic-badge");
		textBlock32.VerticalAlignment = VerticalAlignment.Top;
		((ISupportInitialize)textBlock32).EndInit();
		Controls children33 = grid7.Children;
		TextBlock textBlock34;
		TextBlock textBlock33 = (textBlock34 = new TextBlock());
		((ISupportInitialize)textBlock33).BeginInit();
		children33.Add(textBlock33);
		Grid.SetRow(textBlock34, 1);
		Grid.SetColumn(textBlock34, 1);
		textBlock34.Text = "Attracts the bar. Each detected Pursue box generates a pull force weighted by its confidence and class weight. The effective pull direction is from bar to box center. Default contribution: weight * confidence.";
		textBlock34.Classes.Add("banner-copy");
		textBlock34.TextWrapping = TextWrapping.Wrap;
		((ISupportInitialize)textBlock34).EndInit();
		Controls children34 = grid7.Children;
		TextBlock textBlock36;
		TextBlock textBlock35 = (textBlock36 = new TextBlock());
		((ISupportInitialize)textBlock35).BeginInit();
		children34.Add(textBlock35);
		Grid.SetRow(textBlock36, 2);
		textBlock36.Text = "Avoid";
		textBlock36.Classes.Add("mechanic-badge");
		textBlock36.VerticalAlignment = VerticalAlignment.Top;
		((ISupportInitialize)textBlock36).EndInit();
		Controls children35 = grid7.Children;
		TextBlock textBlock38;
		TextBlock textBlock37 = (textBlock38 = new TextBlock());
		((ISupportInitialize)textBlock37).BeginInit();
		children35.Add(textBlock37);
		Grid.SetRow(textBlock38, 2);
		Grid.SetColumn(textBlock38, 1);
		textBlock38.Text = "Repels the bar. Each detected Avoid box generates a push force away from it. The push gets stronger as the box gets closer to the bar. Default contribution: weight * confidence / distance_norm. Define a custom influence formula for precise collision behavior.";
		textBlock38.Classes.Add("banner-copy");
		textBlock38.TextWrapping = TextWrapping.Wrap;
		((ISupportInitialize)textBlock38).EndInit();
		Controls children36 = grid7.Children;
		TextBlock textBlock40;
		TextBlock textBlock39 = (textBlock40 = new TextBlock());
		((ISupportInitialize)textBlock39).BeginInit();
		children36.Add(textBlock39);
		Grid.SetRow(textBlock40, 3);
		textBlock40.Text = "Progress";
		textBlock40.Classes.Add("mechanic-badge");
		textBlock40.VerticalAlignment = VerticalAlignment.Top;
		((ISupportInitialize)textBlock40).EndInit();
		Controls children37 = grid7.Children;
		TextBlock textBlock42;
		TextBlock textBlock41 = (textBlock42 = new TextBlock());
		((ISupportInitialize)textBlock41).BeginInit();
		children37.Add(textBlock41);
		Grid.SetRow(textBlock42, 3);
		Grid.SetColumn(textBlock42, 1);
		textBlock42.Text = "Tracks the minigame progress bar. If detected, it extends the timeout before recast during minigame. Only one Progress class is needed.";
		textBlock42.Classes.Add("banner-copy");
		textBlock42.TextWrapping = TextWrapping.Wrap;
		((ISupportInitialize)textBlock42).EndInit();
		Controls children38 = grid7.Children;
		TextBlock textBlock44;
		TextBlock textBlock43 = (textBlock44 = new TextBlock());
		((ISupportInitialize)textBlock43).BeginInit();
		children38.Add(textBlock43);
		Grid.SetRow(textBlock44, 4);
		textBlock44.Text = "Observe";
		textBlock44.Classes.Add("mechanic-badge");
		textBlock44.VerticalAlignment = VerticalAlignment.Top;
		((ISupportInitialize)textBlock44).EndInit();
		Controls children39 = grid7.Children;
		TextBlock textBlock46;
		TextBlock textBlock45 = (textBlock46 = new TextBlock());
		((ISupportInitialize)textBlock45).BeginInit();
		children39.Add(textBlock45);
		Grid.SetRow(textBlock46, 4);
		Grid.SetColumn(textBlock46, 1);
		textBlock46.Text = "No steering effect. The class appears in debug vision and the game overlay for diagnostics. Use for classes you want to see but not act on.";
		textBlock46.Classes.Add("banner-copy");
		textBlock46.TextWrapping = TextWrapping.Wrap;
		((ISupportInitialize)textBlock46).EndInit();
		((ISupportInitialize)grid7).EndInit();
		((ISupportInitialize)border4).EndInit();
		Controls children40 = stackPanel14.Children;
		StackPanel stackPanel18;
		StackPanel stackPanel17 = (stackPanel18 = new StackPanel());
		((ISupportInitialize)stackPanel17).BeginInit();
		children40.Add(stackPanel17);
		stackPanel18.Spacing = 6.0;
		Controls children41 = stackPanel18.Children;
		TextBlock textBlock48;
		TextBlock textBlock47 = (textBlock48 = new TextBlock());
		((ISupportInitialize)textBlock47).BeginInit();
		children41.Add(textBlock47);
		textBlock48.Text = "Default behavior (no formulas)";
		textBlock48.Classes.Add("section-title");
		((ISupportInitialize)textBlock48).EndInit();
		Controls children42 = stackPanel18.Children;
		TextBlock textBlock50;
		TextBlock textBlock49 = (textBlock50 = new TextBlock());
		((ISupportInitialize)textBlock49).BeginInit();
		children42.Add(textBlock49);
		textBlock50.Text = "Without any custom formulas, each Pursue box contributes weight * confidence pulling the bar toward it. Each Avoid box contributes weight * confidence / distance_norm pushing away (stronger when close). The final error blends all contributions: (pursuit_weighted_error * avoidance_weighted_error) / total_weight.";
		textBlock50.Classes.Add("banner-copy");
		textBlock50.TextWrapping = TextWrapping.Wrap;
		((ISupportInitialize)textBlock50).EndInit();
		Controls children43 = stackPanel18.Children;
		TextBlock textBlock52;
		TextBlock textBlock51 = (textBlock52 = new TextBlock());
		((ISupportInitialize)textBlock51).BeginInit();
		children43.Add(textBlock51);
		textBlock52.Text = "The middle X of the highest-confidence Pursue box becomes the target for PD control when no Avoid boxes are present. Avoid boxes shift the target away from them.";
		textBlock52.Classes.Add("banner-copy");
		textBlock52.TextWrapping = TextWrapping.Wrap;
		((ISupportInitialize)textBlock52).EndInit();
		((ISupportInitialize)stackPanel18).EndInit();
		((ISupportInitialize)stackPanel14).EndInit();
		((ISupportInitialize)scrollViewer4).EndInit();
		Controls children44 = grid2.Children;
		ScrollViewer scrollViewer6;
		ScrollViewer scrollViewer5 = (scrollViewer6 = new ScrollViewer());
		((ISupportInitialize)scrollViewer5).BeginInit();
		children44.Add(scrollViewer5);
		scrollViewer6.Name = "TabContent2";
		element = scrollViewer6;
		context.AvaloniaNameScope.Register("TabContent2", element);
		Grid.SetRow(scrollViewer6, 2);
		scrollViewer6.Margin = new Thickness(8.0, 4.0, 8.0, 8.0);
		scrollViewer6.VerticalScrollBarVisibility = ScrollBarVisibility.Auto;
		scrollViewer6.IsVisible = false;
		StackPanel stackPanel20;
		StackPanel stackPanel19 = (stackPanel20 = new StackPanel());
		((ISupportInitialize)stackPanel19).BeginInit();
		scrollViewer6.Content = stackPanel19;
		stackPanel20.Spacing = 16.0;
		Controls children45 = stackPanel20.Children;
		StackPanel stackPanel22;
		StackPanel stackPanel21 = (stackPanel22 = new StackPanel());
		((ISupportInitialize)stackPanel21).BeginInit();
		children45.Add(stackPanel21);
		stackPanel22.Spacing = 5.0;
		Controls children46 = stackPanel22.Children;
		TextBlock textBlock54;
		TextBlock textBlock53 = (textBlock54 = new TextBlock());
		((ISupportInitialize)textBlock53).BeginInit();
		children46.Add(textBlock53);
		textBlock54.Text = "Formula variables reference";
		textBlock54.Classes.Add("page-title");
		((ISupportInitialize)textBlock54).EndInit();
		Controls children47 = stackPanel22.Children;
		TextBlock textBlock56;
		TextBlock textBlock55 = (textBlock56 = new TextBlock());
		((ISupportInitialize)textBlock55).BeginInit();
		children47.Add(textBlock55);
		textBlock56.Text = "Two formula types: Influence (per-class) and Steering (final blend). Each has its own set of variables.";
		textBlock56.Classes.Add("page-subtitle");
		textBlock56.TextWrapping = TextWrapping.Wrap;
		((ISupportInitialize)textBlock56).EndInit();
		((ISupportInitialize)stackPanel22).EndInit();
		Controls children48 = stackPanel20.Children;
		Border border6;
		Border border5 = (border6 = new Border());
		((ISupportInitialize)border5).BeginInit();
		children48.Add(border5);
		border6.Classes.Add("feature-card");
		border6.Padding = new Thickness(16.0, 16.0, 16.0, 16.0);
		StackPanel stackPanel24;
		StackPanel stackPanel23 = (stackPanel24 = new StackPanel());
		((ISupportInitialize)stackPanel23).BeginInit();
		border6.Child = stackPanel23;
		stackPanel24.Spacing = 12.0;
		Controls children49 = stackPanel24.Children;
		TextBlock textBlock58;
		TextBlock textBlock57 = (textBlock58 = new TextBlock());
		((ISupportInitialize)textBlock57).BeginInit();
		children49.Add(textBlock57);
		textBlock58.Text = "Influence formula variables (per detection box)";
		textBlock58.Classes.Add("section-title");
		((ISupportInitialize)textBlock58).EndInit();
		Controls children50 = stackPanel24.Children;
		TextBlock textBlock60;
		TextBlock textBlock59 = (textBlock60 = new TextBlock());
		((ISupportInitialize)textBlock59).BeginInit();
		children50.Add(textBlock59);
		textBlock60.Text = "These are available inside a class's Influence Formula field. The result is how strongly this box pulls (Pursue) or pushes (Avoid). Return 0 for no influence.";
		textBlock60.Classes.Add("banner-copy");
		textBlock60.TextWrapping = TextWrapping.Wrap;
		((ISupportInitialize)textBlock60).EndInit();
		Controls children51 = stackPanel24.Children;
		Border border8;
		Border border7 = (border8 = new Border());
		((ISupportInitialize)border7).BeginInit();
		children51.Add(border7);
		border8.Background = new ImmutableSolidColorBrush(404826688u);
		border8.CornerRadius = new CornerRadius(8.0, 8.0, 8.0, 8.0);
		border8.Padding = new Thickness(12.0, 12.0, 12.0, 12.0);
		Grid grid9;
		Grid grid8 = (grid9 = new Grid());
		((ISupportInitialize)grid8).BeginInit();
		border8.Child = grid8;
		RowDefinitions rowDefinitions3 = new RowDefinitions();
		rowDefinitions3.Capacity = 16;
		rowDefinitions3.Add(new RowDefinition(new GridLength(0.0, GridUnitType.Auto)));
		rowDefinitions3.Add(new RowDefinition(new GridLength(0.0, GridUnitType.Auto)));
		rowDefinitions3.Add(new RowDefinition(new GridLength(0.0, GridUnitType.Auto)));
		rowDefinitions3.Add(new RowDefinition(new GridLength(0.0, GridUnitType.Auto)));
		rowDefinitions3.Add(new RowDefinition(new GridLength(0.0, GridUnitType.Auto)));
		rowDefinitions3.Add(new RowDefinition(new GridLength(0.0, GridUnitType.Auto)));
		rowDefinitions3.Add(new RowDefinition(new GridLength(0.0, GridUnitType.Auto)));
		rowDefinitions3.Add(new RowDefinition(new GridLength(0.0, GridUnitType.Auto)));
		rowDefinitions3.Add(new RowDefinition(new GridLength(0.0, GridUnitType.Auto)));
		rowDefinitions3.Add(new RowDefinition(new GridLength(0.0, GridUnitType.Auto)));
		rowDefinitions3.Add(new RowDefinition(new GridLength(0.0, GridUnitType.Auto)));
		rowDefinitions3.Add(new RowDefinition(new GridLength(0.0, GridUnitType.Auto)));
		rowDefinitions3.Add(new RowDefinition(new GridLength(0.0, GridUnitType.Auto)));
		rowDefinitions3.Add(new RowDefinition(new GridLength(0.0, GridUnitType.Auto)));
		rowDefinitions3.Add(new RowDefinition(new GridLength(0.0, GridUnitType.Auto)));
		rowDefinitions3.Add(new RowDefinition(new GridLength(0.0, GridUnitType.Auto)));
		grid9.RowDefinitions = rowDefinitions3;
		ColumnDefinitions columnDefinitions2 = new ColumnDefinitions();
		columnDefinitions2.Capacity = 2;
		columnDefinitions2.Add(new ColumnDefinition(new GridLength(120.0, GridUnitType.Pixel)));
		columnDefinitions2.Add(new ColumnDefinition(new GridLength(1.0, GridUnitType.Star)));
		grid9.ColumnDefinitions = columnDefinitions2;
		grid9.RowSpacing = 6.0;
		grid9.ColumnSpacing = 12.0;
		Controls children52 = grid9.Children;
		TextBlock textBlock62;
		TextBlock textBlock61 = (textBlock62 = new TextBlock());
		((ISupportInitialize)textBlock61).BeginInit();
		children52.Add(textBlock61);
		textBlock62.Text = "x";
		textBlock62.Classes.Add("meta-label");
		((ISupportInitialize)textBlock62).EndInit();
		Controls children53 = grid9.Children;
		TextBlock textBlock64;
		TextBlock textBlock63 = (textBlock64 = new TextBlock());
		((ISupportInitialize)textBlock63).BeginInit();
		children53.Add(textBlock63);
		Grid.SetColumn(textBlock64, 1);
		textBlock64.Text = "Left edge of the detection box in capture-frame pixels";
		textBlock64.Classes.Add("banner-copy");
		((ISupportInitialize)textBlock64).EndInit();
		Controls children54 = grid9.Children;
		TextBlock textBlock66;
		TextBlock textBlock65 = (textBlock66 = new TextBlock());
		((ISupportInitialize)textBlock65).BeginInit();
		children54.Add(textBlock65);
		Grid.SetRow(textBlock66, 1);
		textBlock66.Text = "y";
		textBlock66.Classes.Add("meta-label");
		((ISupportInitialize)textBlock66).EndInit();
		Controls children55 = grid9.Children;
		TextBlock textBlock68;
		TextBlock textBlock67 = (textBlock68 = new TextBlock());
		((ISupportInitialize)textBlock67).BeginInit();
		children55.Add(textBlock67);
		Grid.SetRow(textBlock68, 1);
		Grid.SetColumn(textBlock68, 1);
		textBlock68.Text = "Top edge of the detection box in capture-frame pixels";
		textBlock68.Classes.Add("banner-copy");
		((ISupportInitialize)textBlock68).EndInit();
		Controls children56 = grid9.Children;
		TextBlock textBlock70;
		TextBlock textBlock69 = (textBlock70 = new TextBlock());
		((ISupportInitialize)textBlock69).BeginInit();
		children56.Add(textBlock69);
		Grid.SetRow(textBlock70, 2);
		textBlock70.Text = "width";
		textBlock70.Classes.Add("meta-label");
		((ISupportInitialize)textBlock70).EndInit();
		Controls children57 = grid9.Children;
		TextBlock textBlock72;
		TextBlock textBlock71 = (textBlock72 = new TextBlock());
		((ISupportInitialize)textBlock71).BeginInit();
		children57.Add(textBlock71);
		Grid.SetRow(textBlock72, 2);
		Grid.SetColumn(textBlock72, 1);
		textBlock72.Text = "Width of the detection box in pixels";
		textBlock72.Classes.Add("banner-copy");
		((ISupportInitialize)textBlock72).EndInit();
		Controls children58 = grid9.Children;
		TextBlock textBlock74;
		TextBlock textBlock73 = (textBlock74 = new TextBlock());
		((ISupportInitialize)textBlock73).BeginInit();
		children58.Add(textBlock73);
		Grid.SetRow(textBlock74, 3);
		textBlock74.Text = "height";
		textBlock74.Classes.Add("meta-label");
		((ISupportInitialize)textBlock74).EndInit();
		Controls children59 = grid9.Children;
		TextBlock textBlock76;
		TextBlock textBlock75 = (textBlock76 = new TextBlock());
		((ISupportInitialize)textBlock75).BeginInit();
		children59.Add(textBlock75);
		Grid.SetRow(textBlock76, 3);
		Grid.SetColumn(textBlock76, 1);
		textBlock76.Text = "Height of the detection box in pixels";
		textBlock76.Classes.Add("banner-copy");
		((ISupportInitialize)textBlock76).EndInit();
		Controls children60 = grid9.Children;
		TextBlock textBlock78;
		TextBlock textBlock77 = (textBlock78 = new TextBlock());
		((ISupportInitialize)textBlock77).BeginInit();
		children60.Add(textBlock77);
		Grid.SetRow(textBlock78, 4);
		textBlock78.Text = "center_x";
		textBlock78.Classes.Add("meta-label");
		((ISupportInitialize)textBlock78).EndInit();
		Controls children61 = grid9.Children;
		TextBlock textBlock80;
		TextBlock textBlock79 = (textBlock80 = new TextBlock());
		((ISupportInitialize)textBlock79).BeginInit();
		children61.Add(textBlock79);
		Grid.SetRow(textBlock80, 4);
		Grid.SetColumn(textBlock80, 1);
		textBlock80.Text = "Horizontal center of the box: x + width / 2";
		textBlock80.Classes.Add("banner-copy");
		((ISupportInitialize)textBlock80).EndInit();
		Controls children62 = grid9.Children;
		TextBlock textBlock82;
		TextBlock textBlock81 = (textBlock82 = new TextBlock());
		((ISupportInitialize)textBlock81).BeginInit();
		children62.Add(textBlock81);
		Grid.SetRow(textBlock82, 5);
		textBlock82.Text = "center_y";
		textBlock82.Classes.Add("meta-label");
		((ISupportInitialize)textBlock82).EndInit();
		Controls children63 = grid9.Children;
		TextBlock textBlock84;
		TextBlock textBlock83 = (textBlock84 = new TextBlock());
		((ISupportInitialize)textBlock83).BeginInit();
		children63.Add(textBlock83);
		Grid.SetRow(textBlock84, 5);
		Grid.SetColumn(textBlock84, 1);
		textBlock84.Text = "Vertical center of the box: y + height / 2";
		textBlock84.Classes.Add("banner-copy");
		((ISupportInitialize)textBlock84).EndInit();
		Controls children64 = grid9.Children;
		TextBlock textBlock86;
		TextBlock textBlock85 = (textBlock86 = new TextBlock());
		((ISupportInitialize)textBlock85).BeginInit();
		children64.Add(textBlock85);
		Grid.SetRow(textBlock86, 6);
		textBlock86.Text = "confidence";
		textBlock86.Classes.Add("meta-label");
		((ISupportInitialize)textBlock86).EndInit();
		Controls children65 = grid9.Children;
		TextBlock textBlock88;
		TextBlock textBlock87 = (textBlock88 = new TextBlock());
		((ISupportInitialize)textBlock87).BeginInit();
		children65.Add(textBlock87);
		Grid.SetRow(textBlock88, 6);
		Grid.SetColumn(textBlock88, 1);
		textBlock88.Text = "Model confidence 0-1 for this detection";
		textBlock88.Classes.Add("banner-copy");
		((ISupportInitialize)textBlock88).EndInit();
		Controls children66 = grid9.Children;
		TextBlock textBlock90;
		TextBlock textBlock89 = (textBlock90 = new TextBlock());
		((ISupportInitialize)textBlock89).BeginInit();
		children66.Add(textBlock89);
		Grid.SetRow(textBlock90, 7);
		textBlock90.Text = "class_id";
		textBlock90.Classes.Add("meta-label");
		((ISupportInitialize)textBlock90).EndInit();
		Controls children67 = grid9.Children;
		TextBlock textBlock92;
		TextBlock textBlock91 = (textBlock92 = new TextBlock());
		((ISupportInitialize)textBlock91).BeginInit();
		children67.Add(textBlock91);
		Grid.SetRow(textBlock92, 7);
		Grid.SetColumn(textBlock92, 1);
		textBlock92.Text = "The class ID number from the model";
		textBlock92.Classes.Add("banner-copy");
		((ISupportInitialize)textBlock92).EndInit();
		Controls children68 = grid9.Children;
		TextBlock textBlock94;
		TextBlock textBlock93 = (textBlock94 = new TextBlock());
		((ISupportInitialize)textBlock93).BeginInit();
		children68.Add(textBlock93);
		Grid.SetRow(textBlock94, 8);
		textBlock94.Text = "player_x";
		textBlock94.Classes.Add("meta-label");
		((ISupportInitialize)textBlock94).EndInit();
		Controls children69 = grid9.Children;
		TextBlock textBlock96;
		TextBlock textBlock95 = (textBlock96 = new TextBlock());
		((ISupportInitialize)textBlock95).BeginInit();
		children69.Add(textBlock95);
		Grid.SetRow(textBlock96, 8);
		Grid.SetColumn(textBlock96, 1);
		textBlock96.Text = "Horizontal center of the control bar in capture-frame pixels";
		textBlock96.Classes.Add("banner-copy");
		((ISupportInitialize)textBlock96).EndInit();
		Controls children70 = grid9.Children;
		TextBlock textBlock98;
		TextBlock textBlock97 = (textBlock98 = new TextBlock());
		((ISupportInitialize)textBlock97).BeginInit();
		children70.Add(textBlock97);
		Grid.SetRow(textBlock98, 9);
		textBlock98.Text = "player_width";
		textBlock98.Classes.Add("meta-label");
		((ISupportInitialize)textBlock98).EndInit();
		Controls children71 = grid9.Children;
		TextBlock textBlock100;
		TextBlock textBlock99 = (textBlock100 = new TextBlock());
		((ISupportInitialize)textBlock99).BeginInit();
		children71.Add(textBlock99);
		Grid.SetRow(textBlock100, 9);
		Grid.SetColumn(textBlock100, 1);
		textBlock100.Text = "Width of the control bar in pixels";
		textBlock100.Classes.Add("banner-copy");
		((ISupportInitialize)textBlock100).EndInit();
		Controls children72 = grid9.Children;
		TextBlock textBlock102;
		TextBlock textBlock101 = (textBlock102 = new TextBlock());
		((ISupportInitialize)textBlock101).BeginInit();
		children72.Add(textBlock101);
		Grid.SetRow(textBlock102, 10);
		textBlock102.Text = "distance";
		textBlock102.Classes.Add("meta-label");
		((ISupportInitialize)textBlock102).EndInit();
		Controls children73 = grid9.Children;
		TextBlock textBlock104;
		TextBlock textBlock103 = (textBlock104 = new TextBlock());
		((ISupportInitialize)textBlock103).BeginInit();
		children73.Add(textBlock103);
		Grid.SetRow(textBlock104, 10);
		Grid.SetColumn(textBlock104, 1);
		textBlock104.Text = "Absolute horizontal distance from bar center to box center in pixels (not signed)";
		textBlock104.Classes.Add("banner-copy");
		((ISupportInitialize)textBlock104).EndInit();
		Controls children74 = grid9.Children;
		TextBlock textBlock106;
		TextBlock textBlock105 = (textBlock106 = new TextBlock());
		((ISupportInitialize)textBlock105).BeginInit();
		children74.Add(textBlock105);
		Grid.SetRow(textBlock106, 11);
		textBlock106.Text = "distance_norm";
		textBlock106.Classes.Add("meta-label");
		((ISupportInitialize)textBlock106).EndInit();
		Controls children75 = grid9.Children;
		TextBlock textBlock108;
		TextBlock textBlock107 = (textBlock108 = new TextBlock());
		((ISupportInitialize)textBlock107).BeginInit();
		children75.Add(textBlock107);
		Grid.SetRow(textBlock108, 11);
		Grid.SetColumn(textBlock108, 1);
		textBlock108.Text = "Normalized distance 0-1 relative to frame width";
		textBlock108.Classes.Add("banner-copy");
		((ISupportInitialize)textBlock108).EndInit();
		Controls children76 = grid9.Children;
		TextBlock textBlock110;
		TextBlock textBlock109 = (textBlock110 = new TextBlock());
		((ISupportInitialize)textBlock109).BeginInit();
		children76.Add(textBlock109);
		Grid.SetRow(textBlock110, 12);
		textBlock110.Text = "overlap";
		textBlock110.Classes.Add("meta-label");
		((ISupportInitialize)textBlock110).EndInit();
		Controls children77 = grid9.Children;
		TextBlock textBlock112;
		TextBlock textBlock111 = (textBlock112 = new TextBlock());
		((ISupportInitialize)textBlock111).BeginInit();
		children77.Add(textBlock111);
		Grid.SetRow(textBlock112, 12);
		Grid.SetColumn(textBlock112, 1);
		textBlock112.Text = "Horizontal overlap fraction 0-1 between box and bar: 1 = fully overlapping, 0 = not touching";
		textBlock112.Classes.Add("banner-copy");
		((ISupportInitialize)textBlock112).EndInit();
		Controls children78 = grid9.Children;
		TextBlock textBlock114;
		TextBlock textBlock113 = (textBlock114 = new TextBlock());
		((ISupportInitialize)textBlock113).BeginInit();
		children78.Add(textBlock113);
		Grid.SetRow(textBlock114, 13);
		textBlock114.Text = "direction";
		textBlock114.Classes.Add("meta-label");
		((ISupportInitialize)textBlock114).EndInit();
		Controls children79 = grid9.Children;
		TextBlock textBlock116;
		TextBlock textBlock115 = (textBlock116 = new TextBlock());
		((ISupportInitialize)textBlock115).BeginInit();
		children79.Add(textBlock115);
		Grid.SetRow(textBlock116, 13);
		Grid.SetColumn(textBlock116, 1);
		textBlock116.Text = "-1 if the box is left of the bar, 1 if right of the bar, 0 if centered";
		textBlock116.Classes.Add("banner-copy");
		((ISupportInitialize)textBlock116).EndInit();
		Controls children80 = grid9.Children;
		TextBlock textBlock118;
		TextBlock textBlock117 = (textBlock118 = new TextBlock());
		((ISupportInitialize)textBlock117).BeginInit();
		children80.Add(textBlock117);
		Grid.SetRow(textBlock118, 14);
		textBlock118.Text = "weight";
		textBlock118.Classes.Add("meta-label");
		((ISupportInitialize)textBlock118).EndInit();
		Controls children81 = grid9.Children;
		TextBlock textBlock120;
		TextBlock textBlock119 = (textBlock120 = new TextBlock());
		((ISupportInitialize)textBlock119).BeginInit();
		children81.Add(textBlock119);
		Grid.SetRow(textBlock120, 14);
		Grid.SetColumn(textBlock120, 1);
		textBlock120.Text = "The class weight from the class table";
		textBlock120.Classes.Add("banner-copy");
		((ISupportInitialize)textBlock120).EndInit();
		Controls children82 = grid9.Children;
		TextBlock textBlock122;
		TextBlock textBlock121 = (textBlock122 = new TextBlock());
		((ISupportInitialize)textBlock121).BeginInit();
		children82.Add(textBlock121);
		Grid.SetRow(textBlock122, 15);
		textBlock122.Text = "frame_width";
		textBlock122.Classes.Add("meta-label");
		((ISupportInitialize)textBlock122).EndInit();
		Controls children83 = grid9.Children;
		TextBlock textBlock124;
		TextBlock textBlock123 = (textBlock124 = new TextBlock());
		((ISupportInitialize)textBlock123).BeginInit();
		children83.Add(textBlock123);
		Grid.SetRow(textBlock124, 15);
		Grid.SetColumn(textBlock124, 1);
		textBlock124.Text = "Width of the capture frame in pixels";
		textBlock124.Classes.Add("banner-copy");
		((ISupportInitialize)textBlock124).EndInit();
		((ISupportInitialize)grid9).EndInit();
		((ISupportInitialize)border8).EndInit();
		((ISupportInitialize)stackPanel24).EndInit();
		((ISupportInitialize)border6).EndInit();
		Controls children84 = stackPanel20.Children;
		Border border10;
		Border border9 = (border10 = new Border());
		((ISupportInitialize)border9).BeginInit();
		children84.Add(border9);
		border10.Classes.Add("feature-card");
		border10.Padding = new Thickness(16.0, 16.0, 16.0, 16.0);
		StackPanel stackPanel26;
		StackPanel stackPanel25 = (stackPanel26 = new StackPanel());
		((ISupportInitialize)stackPanel25).BeginInit();
		border10.Child = stackPanel25;
		stackPanel26.Spacing = 12.0;
		Controls children85 = stackPanel26.Children;
		TextBlock textBlock126;
		TextBlock textBlock125 = (textBlock126 = new TextBlock());
		((ISupportInitialize)textBlock125).BeginInit();
		children85.Add(textBlock125);
		textBlock126.Text = "Steering formula variables (final blend)";
		textBlock126.Classes.Add("section-title");
		((ISupportInitialize)textBlock126).EndInit();
		Controls children86 = stackPanel26.Children;
		TextBlock textBlock128;
		TextBlock textBlock127 = (textBlock128 = new TextBlock());
		((ISupportInitialize)textBlock127).BeginInit();
		children86.Add(textBlock127);
		textBlock128.Text = "These are available inside the Final Steering Formula field. The result replaces the default blend and is clamped to (-frame_width, +frame_width) then used as ErrorPixels for PD control.";
		textBlock128.Classes.Add("banner-copy");
		textBlock128.TextWrapping = TextWrapping.Wrap;
		((ISupportInitialize)textBlock128).EndInit();
		Controls children87 = stackPanel26.Children;
		Border border12;
		Border border11 = (border12 = new Border());
		((ISupportInitialize)border11).BeginInit();
		children87.Add(border11);
		border12.Background = new ImmutableSolidColorBrush(404826688u);
		border12.CornerRadius = new CornerRadius(8.0, 8.0, 8.0, 8.0);
		border12.Padding = new Thickness(12.0, 12.0, 12.0, 12.0);
		Grid grid11;
		Grid grid10 = (grid11 = new Grid());
		((ISupportInitialize)grid10).BeginInit();
		border12.Child = grid10;
		RowDefinitions rowDefinitions4 = new RowDefinitions();
		rowDefinitions4.Capacity = 7;
		rowDefinitions4.Add(new RowDefinition(new GridLength(0.0, GridUnitType.Auto)));
		rowDefinitions4.Add(new RowDefinition(new GridLength(0.0, GridUnitType.Auto)));
		rowDefinitions4.Add(new RowDefinition(new GridLength(0.0, GridUnitType.Auto)));
		rowDefinitions4.Add(new RowDefinition(new GridLength(0.0, GridUnitType.Auto)));
		rowDefinitions4.Add(new RowDefinition(new GridLength(0.0, GridUnitType.Auto)));
		rowDefinitions4.Add(new RowDefinition(new GridLength(0.0, GridUnitType.Auto)));
		rowDefinitions4.Add(new RowDefinition(new GridLength(0.0, GridUnitType.Auto)));
		grid11.RowDefinitions = rowDefinitions4;
		ColumnDefinitions columnDefinitions3 = new ColumnDefinitions();
		columnDefinitions3.Capacity = 2;
		columnDefinitions3.Add(new ColumnDefinition(new GridLength(140.0, GridUnitType.Pixel)));
		columnDefinitions3.Add(new ColumnDefinition(new GridLength(1.0, GridUnitType.Star)));
		grid11.ColumnDefinitions = columnDefinitions3;
		grid11.RowSpacing = 6.0;
		grid11.ColumnSpacing = 12.0;
		Controls children88 = grid11.Children;
		TextBlock textBlock130;
		TextBlock textBlock129 = (textBlock130 = new TextBlock());
		((ISupportInitialize)textBlock129).BeginInit();
		children88.Add(textBlock129);
		textBlock130.Text = "pursuit_error";
		textBlock130.Classes.Add("meta-label");
		((ISupportInitialize)textBlock130).EndInit();
		Controls children89 = grid11.Children;
		TextBlock textBlock132;
		TextBlock textBlock131 = (textBlock132 = new TextBlock());
		((ISupportInitialize)textBlock131).BeginInit();
		children89.Add(textBlock131);
		Grid.SetColumn(textBlock132, 1);
		textBlock132.Text = "The weighted average error from all Pursue boxes (signed, in pixels). Positive = target is to the right of the bar.";
		textBlock132.Classes.Add("banner-copy");
		((ISupportInitialize)textBlock132).EndInit();
		Controls children90 = grid11.Children;
		TextBlock textBlock134;
		TextBlock textBlock133 = (textBlock134 = new TextBlock());
		((ISupportInitialize)textBlock133).BeginInit();
		children90.Add(textBlock133);
		Grid.SetRow(textBlock134, 1);
		textBlock134.Text = "avoidance_error";
		textBlock134.Classes.Add("meta-label");
		((ISupportInitialize)textBlock134).EndInit();
		Controls children91 = grid11.Children;
		TextBlock textBlock136;
		TextBlock textBlock135 = (textBlock136 = new TextBlock());
		((ISupportInitialize)textBlock135).BeginInit();
		children91.Add(textBlock135);
		Grid.SetRow(textBlock136, 1);
		Grid.SetColumn(textBlock136, 1);
		textBlock136.Text = "The weighted average error from all Avoid boxes (signed, in pixels). Positive = avoid force is pushing right.";
		textBlock136.Classes.Add("banner-copy");
		((ISupportInitialize)textBlock136).EndInit();
		Controls children92 = grid11.Children;
		TextBlock textBlock138;
		TextBlock textBlock137 = (textBlock138 = new TextBlock());
		((ISupportInitialize)textBlock137).BeginInit();
		children92.Add(textBlock137);
		Grid.SetRow(textBlock138, 2);
		textBlock138.Text = "pursuit_weight";
		textBlock138.Classes.Add("meta-label");
		((ISupportInitialize)textBlock138).EndInit();
		Controls children93 = grid11.Children;
		TextBlock textBlock140;
		TextBlock textBlock139 = (textBlock140 = new TextBlock());
		((ISupportInitialize)textBlock139).BeginInit();
		children93.Add(textBlock139);
		Grid.SetRow(textBlock140, 2);
		Grid.SetColumn(textBlock140, 1);
		textBlock140.Text = "Total accumulated weight from all Pursue boxes";
		textBlock140.Classes.Add("banner-copy");
		((ISupportInitialize)textBlock140).EndInit();
		Controls children94 = grid11.Children;
		TextBlock textBlock142;
		TextBlock textBlock141 = (textBlock142 = new TextBlock());
		((ISupportInitialize)textBlock141).BeginInit();
		children94.Add(textBlock141);
		Grid.SetRow(textBlock142, 3);
		textBlock142.Text = "avoidance_weight";
		textBlock142.Classes.Add("meta-label");
		((ISupportInitialize)textBlock142).EndInit();
		Controls children95 = grid11.Children;
		TextBlock textBlock144;
		TextBlock textBlock143 = (textBlock144 = new TextBlock());
		((ISupportInitialize)textBlock143).BeginInit();
		children95.Add(textBlock143);
		Grid.SetRow(textBlock144, 3);
		Grid.SetColumn(textBlock144, 1);
		textBlock144.Text = "Total accumulated weight from all Avoid boxes";
		textBlock144.Classes.Add("banner-copy");
		((ISupportInitialize)textBlock144).EndInit();
		Controls children96 = grid11.Children;
		TextBlock textBlock146;
		TextBlock textBlock145 = (textBlock146 = new TextBlock());
		((ISupportInitialize)textBlock145).BeginInit();
		children96.Add(textBlock145);
		Grid.SetRow(textBlock146, 4);
		textBlock146.Text = "legacy_error";
		textBlock146.Classes.Add("meta-label");
		((ISupportInitialize)textBlock146).EndInit();
		Controls children97 = grid11.Children;
		TextBlock textBlock148;
		TextBlock textBlock147 = (textBlock148 = new TextBlock());
		((ISupportInitialize)textBlock147).BeginInit();
		children97.Add(textBlock147);
		Grid.SetRow(textBlock148, 4);
		Grid.SetColumn(textBlock148, 1);
		textBlock148.Text = "Simple single-target error: highest-confidence Pursue box center minus bar center (in pixels)";
		textBlock148.Classes.Add("banner-copy");
		((ISupportInitialize)textBlock148).EndInit();
		Controls children98 = grid11.Children;
		TextBlock textBlock150;
		TextBlock textBlock149 = (textBlock150 = new TextBlock());
		((ISupportInitialize)textBlock149).BeginInit();
		children98.Add(textBlock149);
		Grid.SetRow(textBlock150, 5);
		textBlock150.Text = "player_x";
		textBlock150.Classes.Add("meta-label");
		((ISupportInitialize)textBlock150).EndInit();
		Controls children99 = grid11.Children;
		TextBlock textBlock152;
		TextBlock textBlock151 = (textBlock152 = new TextBlock());
		((ISupportInitialize)textBlock151).BeginInit();
		children99.Add(textBlock151);
		Grid.SetRow(textBlock152, 5);
		Grid.SetColumn(textBlock152, 1);
		textBlock152.Text = "Horizontal center of the control bar in capture-frame pixels";
		textBlock152.Classes.Add("banner-copy");
		((ISupportInitialize)textBlock152).EndInit();
		Controls children100 = grid11.Children;
		TextBlock textBlock154;
		TextBlock textBlock153 = (textBlock154 = new TextBlock());
		((ISupportInitialize)textBlock153).BeginInit();
		children100.Add(textBlock153);
		Grid.SetRow(textBlock154, 6);
		textBlock154.Text = "frame_width";
		textBlock154.Classes.Add("meta-label");
		((ISupportInitialize)textBlock154).EndInit();
		Controls children101 = grid11.Children;
		TextBlock textBlock156;
		TextBlock textBlock155 = (textBlock156 = new TextBlock());
		((ISupportInitialize)textBlock155).BeginInit();
		children101.Add(textBlock155);
		Grid.SetRow(textBlock156, 6);
		Grid.SetColumn(textBlock156, 1);
		textBlock156.Text = "Width of the capture frame in pixels";
		textBlock156.Classes.Add("banner-copy");
		((ISupportInitialize)textBlock156).EndInit();
		((ISupportInitialize)grid11).EndInit();
		((ISupportInitialize)border12).EndInit();
		((ISupportInitialize)stackPanel26).EndInit();
		((ISupportInitialize)border10).EndInit();
		Controls children102 = stackPanel20.Children;
		StackPanel stackPanel28;
		StackPanel stackPanel27 = (stackPanel28 = new StackPanel());
		((ISupportInitialize)stackPanel27).BeginInit();
		children102.Add(stackPanel27);
		stackPanel28.Spacing = 6.0;
		Controls children103 = stackPanel28.Children;
		TextBlock textBlock158;
		TextBlock textBlock157 = (textBlock158 = new TextBlock());
		((ISupportInitialize)textBlock157).BeginInit();
		children103.Add(textBlock157);
		textBlock158.Text = "Supported operators and functions";
		textBlock158.Classes.Add("section-title");
		((ISupportInitialize)textBlock158).EndInit();
		Controls children104 = stackPanel28.Children;
		TextBlock textBlock160;
		TextBlock textBlock159 = (textBlock160 = new TextBlock());
		((ISupportInitialize)textBlock159).BeginInit();
		children104.Add(textBlock159);
		textBlock160.Text = "Arithmetic: + - * / % ^ ( ) | Comparison: == != < > <= >= | Logic: || && ! | Ternary: if(cond, then, else)";
		textBlock160.Classes.Add("banner-copy");
		textBlock160.TextWrapping = TextWrapping.Wrap;
		((ISupportInitialize)textBlock160).EndInit();
		Controls children105 = stackPanel28.Children;
		TextBlock textBlock162;
		TextBlock textBlock161 = (textBlock162 = new TextBlock());
		((ISupportInitialize)textBlock161).BeginInit();
		children105.Add(textBlock161);
		textBlock162.Text = "abs(x) sqrt(x) round(x) floor(x) ceil(x) sign(x) | min(a,b) max(a,b) pow(a,b) | clamp(x,lo,hi) lerp(a,b,t) | Constants: pi e true(1) false(0)";
		textBlock162.Classes.Add("banner-copy");
		textBlock162.TextWrapping = TextWrapping.Wrap;
		((ISupportInitialize)textBlock162).EndInit();
		((ISupportInitialize)stackPanel28).EndInit();
		((ISupportInitialize)stackPanel20).EndInit();
		((ISupportInitialize)scrollViewer6).EndInit();
		Controls children106 = grid2.Children;
		ScrollViewer scrollViewer8;
		ScrollViewer scrollViewer7 = (scrollViewer8 = new ScrollViewer());
		((ISupportInitialize)scrollViewer7).BeginInit();
		children106.Add(scrollViewer7);
		scrollViewer8.Name = "TabContent3";
		element = scrollViewer8;
		context.AvaloniaNameScope.Register("TabContent3", element);
		Grid.SetRow(scrollViewer8, 2);
		scrollViewer8.Margin = new Thickness(8.0, 4.0, 8.0, 8.0);
		scrollViewer8.VerticalScrollBarVisibility = ScrollBarVisibility.Auto;
		scrollViewer8.IsVisible = false;
		StackPanel stackPanel30;
		StackPanel stackPanel29 = (stackPanel30 = new StackPanel());
		((ISupportInitialize)stackPanel29).BeginInit();
		scrollViewer8.Content = stackPanel29;
		stackPanel30.Spacing = 18.0;
		Controls children107 = stackPanel30.Children;
		StackPanel stackPanel32;
		StackPanel stackPanel31 = (stackPanel32 = new StackPanel());
		((ISupportInitialize)stackPanel31).BeginInit();
		children107.Add(stackPanel31);
		stackPanel32.Spacing = 5.0;
		Controls children108 = stackPanel32.Children;
		TextBlock textBlock164;
		TextBlock textBlock163 = (textBlock164 = new TextBlock());
		((ISupportInitialize)textBlock163).BeginInit();
		children108.Add(textBlock163);
		textBlock164.Text = "Formula examples";
		textBlock164.Classes.Add("page-title");
		((ISupportInitialize)textBlock164).EndInit();
		Controls children109 = stackPanel32.Children;
		TextBlock textBlock166;
		TextBlock textBlock165 = (textBlock166 = new TextBlock());
		((ISupportInitialize)textBlock165).BeginInit();
		children109.Add(textBlock165);
		textBlock166.Text = "Real formulas for common fishing scenarios. Write these inside Influence Formula or Final Steering Formula depending on the table.";
		textBlock166.Classes.Add("page-subtitle");
		textBlock166.TextWrapping = TextWrapping.Wrap;
		((ISupportInitialize)textBlock166).EndInit();
		((ISupportInitialize)stackPanel32).EndInit();
		Controls children110 = stackPanel30.Children;
		Border border14;
		Border border13 = (border14 = new Border());
		((ISupportInitialize)border13).BeginInit();
		children110.Add(border13);
		border14.Classes.Add("feature-card");
		border14.Padding = new Thickness(16.0, 16.0, 16.0, 16.0);
		StackPanel stackPanel34;
		StackPanel stackPanel33 = (stackPanel34 = new StackPanel());
		((ISupportInitialize)stackPanel33).BeginInit();
		border14.Child = stackPanel33;
		stackPanel34.Spacing = 12.0;
		Controls children111 = stackPanel34.Children;
		TextBlock textBlock168;
		TextBlock textBlock167 = (textBlock168 = new TextBlock());
		((ISupportInitialize)textBlock167).BeginInit();
		children111.Add(textBlock167);
		textBlock168.Text = "Influence formulas (per class)";
		textBlock168.Classes.Add("section-title");
		((ISupportInitialize)textBlock168).EndInit();
		Controls children112 = stackPanel34.Children;
		Grid grid13;
		Grid grid12 = (grid13 = new Grid());
		((ISupportInitialize)grid12).BeginInit();
		children112.Add(grid12);
		RowDefinitions rowDefinitions5 = new RowDefinitions();
		rowDefinitions5.Capacity = 7;
		rowDefinitions5.Add(new RowDefinition(new GridLength(0.0, GridUnitType.Auto)));
		rowDefinitions5.Add(new RowDefinition(new GridLength(0.0, GridUnitType.Auto)));
		rowDefinitions5.Add(new RowDefinition(new GridLength(0.0, GridUnitType.Auto)));
		rowDefinitions5.Add(new RowDefinition(new GridLength(0.0, GridUnitType.Auto)));
		rowDefinitions5.Add(new RowDefinition(new GridLength(0.0, GridUnitType.Auto)));
		rowDefinitions5.Add(new RowDefinition(new GridLength(0.0, GridUnitType.Auto)));
		rowDefinitions5.Add(new RowDefinition(new GridLength(0.0, GridUnitType.Auto)));
		grid13.RowDefinitions = rowDefinitions5;
		grid13.RowSpacing = 16.0;
		grid13.ColumnSpacing = 14.0;
		Controls children113 = grid13.Children;
		StackPanel stackPanel36;
		StackPanel stackPanel35 = (stackPanel36 = new StackPanel());
		((ISupportInitialize)stackPanel35).BeginInit();
		children113.Add(stackPanel35);
		Grid.SetRow(stackPanel36, 0);
		Controls children114 = stackPanel36.Children;
		TextBlock textBlock170;
		TextBlock textBlock169 = (textBlock170 = new TextBlock());
		((ISupportInitialize)textBlock169).BeginInit();
		children114.Add(textBlock169);
		textBlock170.Text = "Ignore far-away detections";
		textBlock170.Classes.Add("field-label");
		((ISupportInitialize)textBlock170).EndInit();
		Controls children115 = stackPanel36.Children;
		Border border16;
		Border border15 = (border16 = new Border());
		((ISupportInitialize)border15).BeginInit();
		children115.Add(border15);
		border16.Background = new ImmutableSolidColorBrush(404826688u);
		border16.CornerRadius = new CornerRadius(6.0, 6.0, 6.0, 6.0);
		border16.Padding = new Thickness(10.0, 6.0, 10.0, 6.0);
		TextBlock textBlock172;
		TextBlock textBlock171 = (textBlock172 = new TextBlock());
		((ISupportInitialize)textBlock171).BeginInit();
		border16.Child = textBlock171;
		textBlock172.Text = "if(distance > 300, 0, weight * confidence)";
		textBlock172.FontFamily = new FontFamily(((IUriContext)context).BaseUri, "Consolas");
		textBlock172.FontSize = 13.0;
		((ISupportInitialize)textBlock172).EndInit();
		((ISupportInitialize)border16).EndInit();
		Controls children116 = stackPanel36.Children;
		TextBlock textBlock174;
		TextBlock textBlock173 = (textBlock174 = new TextBlock());
		((ISupportInitialize)textBlock173).BeginInit();
		children116.Add(textBlock173);
		textBlock174.Text = "Boxes beyond 300 pixels have no influence. Closer boxes use default weight * confidence.";
		textBlock174.Classes.Add("banner-copy");
		textBlock174.TextWrapping = TextWrapping.Wrap;
		((ISupportInitialize)textBlock174).EndInit();
		((ISupportInitialize)stackPanel36).EndInit();
		Controls children117 = grid13.Children;
		StackPanel stackPanel38;
		StackPanel stackPanel37 = (stackPanel38 = new StackPanel());
		((ISupportInitialize)stackPanel37).BeginInit();
		children117.Add(stackPanel37);
		Grid.SetRow(stackPanel38, 1);
		Controls children118 = stackPanel38.Children;
		TextBlock textBlock176;
		TextBlock textBlock175 = (textBlock176 = new TextBlock());
		((ISupportInitialize)textBlock175).BeginInit();
		children118.Add(textBlock175);
		textBlock176.Text = "Strong collision avoidance";
		textBlock176.Classes.Add("field-label");
		((ISupportInitialize)textBlock176).EndInit();
		Controls children119 = stackPanel38.Children;
		Border border18;
		Border border17 = (border18 = new Border());
		((ISupportInitialize)border17).BeginInit();
		children119.Add(border17);
		border18.Background = new ImmutableSolidColorBrush(404826688u);
		border18.CornerRadius = new CornerRadius(6.0, 6.0, 6.0, 6.0);
		border18.Padding = new Thickness(10.0, 6.0, 10.0, 6.0);
		TextBlock textBlock178;
		TextBlock textBlock177 = (textBlock178 = new TextBlock());
		((ISupportInitialize)textBlock177).BeginInit();
		border18.Child = textBlock177;
		textBlock178.Text = "if(overlap > 0.3, weight * 20, weight * confidence / max(distance_norm, 0.05))";
		textBlock178.FontFamily = new FontFamily(((IUriContext)context).BaseUri, "Consolas");
		textBlock178.FontSize = 13.0;
		((ISupportInitialize)textBlock178).EndInit();
		((ISupportInitialize)border18).EndInit();
		Controls children120 = stackPanel38.Children;
		TextBlock textBlock180;
		TextBlock textBlock179 = (textBlock180 = new TextBlock());
		((ISupportInitialize)textBlock179).BeginInit();
		children120.Add(textBlock179);
		textBlock180.Text = "When an Avoid box overlaps the bar by more than 30%, apply extreme repulsion (weight * 20). Otherwise default distance-weighted avoidance, clamped to avoid division by zero.";
		textBlock180.Classes.Add("banner-copy");
		textBlock180.TextWrapping = TextWrapping.Wrap;
		((ISupportInitialize)textBlock180).EndInit();
		((ISupportInitialize)stackPanel38).EndInit();
		Controls children121 = grid13.Children;
		StackPanel stackPanel40;
		StackPanel stackPanel39 = (stackPanel40 = new StackPanel());
		((ISupportInitialize)stackPanel39).BeginInit();
		children121.Add(stackPanel39);
		Grid.SetRow(stackPanel40, 2);
		Controls children122 = stackPanel40.Children;
		TextBlock textBlock182;
		TextBlock textBlock181 = (textBlock182 = new TextBlock());
		((ISupportInitialize)textBlock181).BeginInit();
		children122.Add(textBlock181);
		textBlock182.Text = "Direction-sensitive pursuit";
		textBlock182.Classes.Add("field-label");
		((ISupportInitialize)textBlock182).EndInit();
		Controls children123 = stackPanel40.Children;
		Border border20;
		Border border19 = (border20 = new Border());
		((ISupportInitialize)border19).BeginInit();
		children123.Add(border19);
		border20.Background = new ImmutableSolidColorBrush(404826688u);
		border20.CornerRadius = new CornerRadius(6.0, 6.0, 6.0, 6.0);
		border20.Padding = new Thickness(10.0, 6.0, 10.0, 6.0);
		TextBlock textBlock184;
		TextBlock textBlock183 = (textBlock184 = new TextBlock());
		((ISupportInitialize)textBlock183).BeginInit();
		border20.Child = textBlock183;
		textBlock184.Text = "weight * confidence * (1 + direction * 0.5)";
		textBlock184.FontFamily = new FontFamily(((IUriContext)context).BaseUri, "Consolas");
		textBlock184.FontSize = 13.0;
		((ISupportInitialize)textBlock184).EndInit();
		((ISupportInitialize)border20).EndInit();
		Controls children124 = stackPanel40.Children;
		TextBlock textBlock186;
		TextBlock textBlock185 = (textBlock186 = new TextBlock());
		((ISupportInitialize)textBlock185).BeginInit();
		children124.Add(textBlock185);
		textBlock186.Text = "Boosts pursuit force by 50% to the right, reduces by 50% to the left. Useful if your bar moves faster in one direction.";
		textBlock186.Classes.Add("banner-copy");
		textBlock186.TextWrapping = TextWrapping.Wrap;
		((ISupportInitialize)textBlock186).EndInit();
		((ISupportInitialize)stackPanel40).EndInit();
		Controls children125 = grid13.Children;
		StackPanel stackPanel42;
		StackPanel stackPanel41 = (stackPanel42 = new StackPanel());
		((ISupportInitialize)stackPanel41).BeginInit();
		children125.Add(stackPanel41);
		Grid.SetRow(stackPanel42, 3);
		Controls children126 = stackPanel42.Children;
		TextBlock textBlock188;
		TextBlock textBlock187 = (textBlock188 = new TextBlock());
		((ISupportInitialize)textBlock187).BeginInit();
		children126.Add(textBlock187);
		textBlock188.Text = "Confidence gate";
		textBlock188.Classes.Add("field-label");
		((ISupportInitialize)textBlock188).EndInit();
		Controls children127 = stackPanel42.Children;
		Border border22;
		Border border21 = (border22 = new Border());
		((ISupportInitialize)border21).BeginInit();
		children127.Add(border21);
		border22.Background = new ImmutableSolidColorBrush(404826688u);
		border22.CornerRadius = new CornerRadius(6.0, 6.0, 6.0, 6.0);
		border22.Padding = new Thickness(10.0, 6.0, 10.0, 6.0);
		TextBlock textBlock190;
		TextBlock textBlock189 = (textBlock190 = new TextBlock());
		((ISupportInitialize)textBlock189).BeginInit();
		border22.Child = textBlock189;
		textBlock190.Text = "if(confidence < 0.6, 0, weight)";
		textBlock190.FontFamily = new FontFamily(((IUriContext)context).BaseUri, "Consolas");
		textBlock190.FontSize = 13.0;
		((ISupportInitialize)textBlock190).EndInit();
		((ISupportInitialize)border22).EndInit();
		Controls children128 = stackPanel42.Children;
		TextBlock textBlock192;
		TextBlock textBlock191 = (textBlock192 = new TextBlock());
		((ISupportInitialize)textBlock191).BeginInit();
		children128.Add(textBlock191);
		textBlock192.Text = "Only trust detections with confidence above 60%. Below that, ignore entirely. Use when your model has many false positives.";
		textBlock192.Classes.Add("banner-copy");
		textBlock192.TextWrapping = TextWrapping.Wrap;
		((ISupportInitialize)textBlock192).EndInit();
		((ISupportInitialize)stackPanel42).EndInit();
		Controls children129 = grid13.Children;
		StackPanel stackPanel44;
		StackPanel stackPanel43 = (stackPanel44 = new StackPanel());
		((ISupportInitialize)stackPanel43).BeginInit();
		children129.Add(stackPanel43);
		Grid.SetRow(stackPanel44, 4);
		Controls children130 = stackPanel44.Children;
		TextBlock textBlock194;
		TextBlock textBlock193 = (textBlock194 = new TextBlock());
		((ISupportInitialize)textBlock193).BeginInit();
		children130.Add(textBlock193);
		textBlock194.Text = "Size-based priority";
		textBlock194.Classes.Add("field-label");
		((ISupportInitialize)textBlock194).EndInit();
		Controls children131 = stackPanel44.Children;
		Border border24;
		Border border23 = (border24 = new Border());
		((ISupportInitialize)border23).BeginInit();
		children131.Add(border23);
		border24.Background = new ImmutableSolidColorBrush(404826688u);
		border24.CornerRadius = new CornerRadius(6.0, 6.0, 6.0, 6.0);
		border24.Padding = new Thickness(10.0, 6.0, 10.0, 6.0);
		TextBlock textBlock196;
		TextBlock textBlock195 = (textBlock196 = new TextBlock());
		((ISupportInitialize)textBlock195).BeginInit();
		border24.Child = textBlock195;
		textBlock196.Text = "weight * confidence * sqrt(width * height) / 20";
		textBlock196.FontFamily = new FontFamily(((IUriContext)context).BaseUri, "Consolas");
		textBlock196.FontSize = 13.0;
		((ISupportInitialize)textBlock196).EndInit();
		((ISupportInitialize)border24).EndInit();
		Controls children132 = stackPanel44.Children;
		TextBlock textBlock198;
		TextBlock textBlock197 = (textBlock198 = new TextBlock());
		((ISupportInitialize)textBlock197).BeginInit();
		children132.Add(textBlock197);
		textBlock198.Text = "Larger boxes get more influence than smaller ones. Useful when big fish are more important to track than small fish.";
		textBlock198.Classes.Add("banner-copy");
		textBlock198.TextWrapping = TextWrapping.Wrap;
		((ISupportInitialize)textBlock198).EndInit();
		((ISupportInitialize)stackPanel44).EndInit();
		Controls children133 = grid13.Children;
		StackPanel stackPanel46;
		StackPanel stackPanel45 = (stackPanel46 = new StackPanel());
		((ISupportInitialize)stackPanel45).BeginInit();
		children133.Add(stackPanel45);
		Grid.SetRow(stackPanel46, 5);
		Controls children134 = stackPanel46.Children;
		TextBlock textBlock200;
		TextBlock textBlock199 = (textBlock200 = new TextBlock());
		((ISupportInitialize)textBlock199).BeginInit();
		children134.Add(textBlock199);
		textBlock200.Text = "Dead zone around bar";
		textBlock200.Classes.Add("field-label");
		((ISupportInitialize)textBlock200).EndInit();
		Controls children135 = stackPanel46.Children;
		Border border26;
		Border border25 = (border26 = new Border());
		((ISupportInitialize)border25).BeginInit();
		children135.Add(border25);
		border26.Background = new ImmutableSolidColorBrush(404826688u);
		border26.CornerRadius = new CornerRadius(6.0, 6.0, 6.0, 6.0);
		border26.Padding = new Thickness(10.0, 6.0, 10.0, 6.0);
		TextBlock textBlock202;
		TextBlock textBlock201 = (textBlock202 = new TextBlock());
		((ISupportInitialize)textBlock201).BeginInit();
		border26.Child = textBlock201;
		textBlock202.Text = "if(distance < player_width * 0.5, 0, weight * confidence)";
		textBlock202.FontFamily = new FontFamily(((IUriContext)context).BaseUri, "Consolas");
		textBlock202.FontSize = 13.0;
		((ISupportInitialize)textBlock202).EndInit();
		((ISupportInitialize)border26).EndInit();
		Controls children136 = stackPanel46.Children;
		TextBlock textBlock204;
		TextBlock textBlock203 = (textBlock204 = new TextBlock());
		((ISupportInitialize)textBlock203).BeginInit();
		children136.Add(textBlock203);
		textBlock204.Text = "Ignore boxes that are within half the bar width of the bar center. The bar doesn't need to move for very close targets.";
		textBlock204.Classes.Add("banner-copy");
		textBlock204.TextWrapping = TextWrapping.Wrap;
		((ISupportInitialize)textBlock204).EndInit();
		((ISupportInitialize)stackPanel46).EndInit();
		Controls children137 = grid13.Children;
		StackPanel stackPanel48;
		StackPanel stackPanel47 = (stackPanel48 = new StackPanel());
		((ISupportInitialize)stackPanel47).BeginInit();
		children137.Add(stackPanel47);
		Grid.SetRow(stackPanel48, 6);
		Controls children138 = stackPanel48.Children;
		TextBlock textBlock206;
		TextBlock textBlock205 = (textBlock206 = new TextBlock());
		((ISupportInitialize)textBlock205).BeginInit();
		children138.Add(textBlock205);
		textBlock206.Text = "Exponential falloff avoidance";
		textBlock206.Classes.Add("field-label");
		((ISupportInitialize)textBlock206).EndInit();
		Controls children139 = stackPanel48.Children;
		Border border28;
		Border border27 = (border28 = new Border());
		((ISupportInitialize)border27).BeginInit();
		children139.Add(border27);
		border28.Background = new ImmutableSolidColorBrush(404826688u);
		border28.CornerRadius = new CornerRadius(6.0, 6.0, 6.0, 6.0);
		border28.Padding = new Thickness(10.0, 6.0, 10.0, 6.0);
		TextBlock textBlock208;
		TextBlock textBlock207 = (textBlock208 = new TextBlock());
		((ISupportInitialize)textBlock207).BeginInit();
		border28.Child = textBlock207;
		textBlock208.Text = "weight * confidence * pow(0.5, distance_norm * 10)";
		textBlock208.FontFamily = new FontFamily(((IUriContext)context).BaseUri, "Consolas");
		textBlock208.FontSize = 13.0;
		((ISupportInitialize)textBlock208).EndInit();
		((ISupportInitialize)border28).EndInit();
		Controls children140 = stackPanel48.Children;
		TextBlock textBlock210;
		TextBlock textBlock209 = (textBlock210 = new TextBlock());
		((ISupportInitialize)textBlock209).BeginInit();
		children140.Add(textBlock209);
		textBlock210.Text = "Repulsion decays exponentially as distance increases. At distance_norm 0.1 = factor 0.5, at 0.5 = factor 0.001. Almost no effect beyond 30% of frame width.";
		textBlock210.Classes.Add("banner-copy");
		textBlock210.TextWrapping = TextWrapping.Wrap;
		((ISupportInitialize)textBlock210).EndInit();
		((ISupportInitialize)stackPanel48).EndInit();
		((ISupportInitialize)grid13).EndInit();
		((ISupportInitialize)stackPanel34).EndInit();
		((ISupportInitialize)border14).EndInit();
		Controls children141 = stackPanel30.Children;
		Border border30;
		Border border29 = (border30 = new Border());
		((ISupportInitialize)border29).BeginInit();
		children141.Add(border29);
		border30.Classes.Add("feature-card");
		border30.Padding = new Thickness(16.0, 16.0, 16.0, 16.0);
		StackPanel stackPanel50;
		StackPanel stackPanel49 = (stackPanel50 = new StackPanel());
		((ISupportInitialize)stackPanel49).BeginInit();
		border30.Child = stackPanel49;
		stackPanel50.Spacing = 12.0;
		Controls children142 = stackPanel50.Children;
		TextBlock textBlock212;
		TextBlock textBlock211 = (textBlock212 = new TextBlock());
		((ISupportInitialize)textBlock211).BeginInit();
		children142.Add(textBlock211);
		textBlock212.Text = "Steering formulas (final blend)";
		textBlock212.Classes.Add("section-title");
		((ISupportInitialize)textBlock212).EndInit();
		Controls children143 = stackPanel50.Children;
		Grid grid15;
		Grid grid14 = (grid15 = new Grid());
		((ISupportInitialize)grid14).BeginInit();
		children143.Add(grid14);
		RowDefinitions rowDefinitions6 = new RowDefinitions();
		rowDefinitions6.Capacity = 5;
		rowDefinitions6.Add(new RowDefinition(new GridLength(0.0, GridUnitType.Auto)));
		rowDefinitions6.Add(new RowDefinition(new GridLength(0.0, GridUnitType.Auto)));
		rowDefinitions6.Add(new RowDefinition(new GridLength(0.0, GridUnitType.Auto)));
		rowDefinitions6.Add(new RowDefinition(new GridLength(0.0, GridUnitType.Auto)));
		rowDefinitions6.Add(new RowDefinition(new GridLength(0.0, GridUnitType.Auto)));
		grid15.RowDefinitions = rowDefinitions6;
		grid15.RowSpacing = 16.0;
		grid15.ColumnSpacing = 14.0;
		Controls children144 = grid15.Children;
		StackPanel stackPanel52;
		StackPanel stackPanel51 = (stackPanel52 = new StackPanel());
		((ISupportInitialize)stackPanel51).BeginInit();
		children144.Add(stackPanel51);
		Grid.SetRow(stackPanel52, 0);
		Controls children145 = stackPanel52.Children;
		TextBlock textBlock214;
		TextBlock textBlock213 = (textBlock214 = new TextBlock());
		((ISupportInitialize)textBlock213).BeginInit();
		children145.Add(textBlock213);
		textBlock214.Text = "Ignore avoidance entirely";
		textBlock214.Classes.Add("field-label");
		((ISupportInitialize)textBlock214).EndInit();
		Controls children146 = stackPanel52.Children;
		Border border32;
		Border border31 = (border32 = new Border());
		((ISupportInitialize)border31).BeginInit();
		children146.Add(border31);
		border32.Background = new ImmutableSolidColorBrush(404826688u);
		border32.CornerRadius = new CornerRadius(6.0, 6.0, 6.0, 6.0);
		border32.Padding = new Thickness(10.0, 6.0, 10.0, 6.0);
		TextBlock textBlock216;
		TextBlock textBlock215 = (textBlock216 = new TextBlock());
		((ISupportInitialize)textBlock215).BeginInit();
		border32.Child = textBlock215;
		textBlock216.Text = "pursuit_error";
		textBlock216.FontFamily = new FontFamily(((IUriContext)context).BaseUri, "Consolas");
		textBlock216.FontSize = 13.0;
		((ISupportInitialize)textBlock216).EndInit();
		((ISupportInitialize)border32).EndInit();
		Controls children147 = stackPanel52.Children;
		TextBlock textBlock218;
		TextBlock textBlock217 = (textBlock218 = new TextBlock());
		((ISupportInitialize)textBlock217).BeginInit();
		children147.Add(textBlock217);
		textBlock218.Text = "Pure pursuit of the fish, ignoring all Avoid classes and weights.";
		textBlock218.Classes.Add("banner-copy");
		textBlock218.TextWrapping = TextWrapping.Wrap;
		((ISupportInitialize)textBlock218).EndInit();
		((ISupportInitialize)stackPanel52).EndInit();
		Controls children148 = grid15.Children;
		StackPanel stackPanel54;
		StackPanel stackPanel53 = (stackPanel54 = new StackPanel());
		((ISupportInitialize)stackPanel53).BeginInit();
		children148.Add(stackPanel53);
		Grid.SetRow(stackPanel54, 1);
		Controls children149 = stackPanel54.Children;
		TextBlock textBlock220;
		TextBlock textBlock219 = (textBlock220 = new TextBlock());
		((ISupportInitialize)textBlock219).BeginInit();
		children149.Add(textBlock219);
		textBlock220.Text = "Dodge-first steering";
		textBlock220.Classes.Add("field-label");
		((ISupportInitialize)textBlock220).EndInit();
		Controls children150 = stackPanel54.Children;
		Border border34;
		Border border33 = (border34 = new Border());
		((ISupportInitialize)border33).BeginInit();
		children150.Add(border33);
		border34.Background = new ImmutableSolidColorBrush(404826688u);
		border34.CornerRadius = new CornerRadius(6.0, 6.0, 6.0, 6.0);
		border34.Padding = new Thickness(10.0, 6.0, 10.0, 6.0);
		TextBlock textBlock222;
		TextBlock textBlock221 = (textBlock222 = new TextBlock());
		((ISupportInitialize)textBlock221).BeginInit();
		border34.Child = textBlock221;
		textBlock222.Text = "if(abs(avoidance_error) > 10, avoidance_error * 2, pursuit_error * 0.8)";
		textBlock222.FontFamily = new FontFamily(((IUriContext)context).BaseUri, "Consolas");
		textBlock222.FontSize = 13.0;
		((ISupportInitialize)textBlock222).EndInit();
		((ISupportInitialize)border34).EndInit();
		Controls children151 = stackPanel54.Children;
		TextBlock textBlock224;
		TextBlock textBlock223 = (textBlock224 = new TextBlock());
		((ISupportInitialize)textBlock223).BeginInit();
		children151.Add(textBlock223);
		textBlock224.Text = "If an Avoid box is close enough to produce more than 10 pixels of error, prioritize dodging at double strength. Otherwise pursue the fish at 80% normal speed.";
		textBlock224.Classes.Add("banner-copy");
		textBlock224.TextWrapping = TextWrapping.Wrap;
		((ISupportInitialize)textBlock224).EndInit();
		((ISupportInitialize)stackPanel54).EndInit();
		Controls children152 = grid15.Children;
		StackPanel stackPanel56;
		StackPanel stackPanel55 = (stackPanel56 = new StackPanel());
		((ISupportInitialize)stackPanel55).BeginInit();
		children152.Add(stackPanel55);
		Grid.SetRow(stackPanel56, 2);
		Controls children153 = stackPanel56.Children;
		TextBlock textBlock226;
		TextBlock textBlock225 = (textBlock226 = new TextBlock());
		((ISupportInitialize)textBlock225).BeginInit();
		children153.Add(textBlock225);
		textBlock226.Text = "Weighted blend with dead zone";
		textBlock226.Classes.Add("field-label");
		((ISupportInitialize)textBlock226).EndInit();
		Controls children154 = stackPanel56.Children;
		Border border36;
		Border border35 = (border36 = new Border());
		((ISupportInitialize)border35).BeginInit();
		children154.Add(border35);
		border36.Background = new ImmutableSolidColorBrush(404826688u);
		border36.CornerRadius = new CornerRadius(6.0, 6.0, 6.0, 6.0);
		border36.Padding = new Thickness(10.0, 6.0, 10.0, 6.0);
		TextBlock textBlock228;
		TextBlock textBlock227 = (textBlock228 = new TextBlock());
		((ISupportInitialize)textBlock227).BeginInit();
		border36.Child = textBlock227;
		textBlock228.Text = "if(abs(legacy_error) < 5, 0, (pursuit_error * pursuit_weight + avoidance_error * avoidance_weight) / max(pursuit_weight + avoidance_weight, 0.001))";
		textBlock228.FontFamily = new FontFamily(((IUriContext)context).BaseUri, "Consolas");
		textBlock228.FontSize = 13.0;
		((ISupportInitialize)textBlock228).EndInit();
		((ISupportInitialize)border36).EndInit();
		Controls children155 = stackPanel56.Children;
		TextBlock textBlock230;
		TextBlock textBlock229 = (textBlock230 = new TextBlock());
		((ISupportInitialize)textBlock229).BeginInit();
		children155.Add(textBlock229);
		textBlock230.Text = "If the bar is within 5 pixels of the highest-confidence fish, do nothing (dead zone). Otherwise use the standard weighted blend of all Pursue and Avoid boxes.";
		textBlock230.Classes.Add("banner-copy");
		textBlock230.TextWrapping = TextWrapping.Wrap;
		((ISupportInitialize)textBlock230).EndInit();
		((ISupportInitialize)stackPanel56).EndInit();
		Controls children156 = grid15.Children;
		StackPanel stackPanel58;
		StackPanel stackPanel57 = (stackPanel58 = new StackPanel());
		((ISupportInitialize)stackPanel57).BeginInit();
		children156.Add(stackPanel57);
		Grid.SetRow(stackPanel58, 3);
		Controls children157 = stackPanel58.Children;
		TextBlock textBlock232;
		TextBlock textBlock231 = (textBlock232 = new TextBlock());
		((ISupportInitialize)textBlock231).BeginInit();
		children157.Add(textBlock231);
		textBlock232.Text = "Aggressive pursuit override";
		textBlock232.Classes.Add("field-label");
		((ISupportInitialize)textBlock232).EndInit();
		Controls children158 = stackPanel58.Children;
		Border border38;
		Border border37 = (border38 = new Border());
		((ISupportInitialize)border37).BeginInit();
		children158.Add(border37);
		border38.Background = new ImmutableSolidColorBrush(404826688u);
		border38.CornerRadius = new CornerRadius(6.0, 6.0, 6.0, 6.0);
		border38.Padding = new Thickness(10.0, 6.0, 10.0, 6.0);
		TextBlock textBlock234;
		TextBlock textBlock233 = (textBlock234 = new TextBlock());
		((ISupportInitialize)textBlock233).BeginInit();
		border38.Child = textBlock233;
		textBlock234.Text = "pursuit_error * 1.5 + avoidance_error * 0.3";
		textBlock234.FontFamily = new FontFamily(((IUriContext)context).BaseUri, "Consolas");
		textBlock234.FontSize = 13.0;
		((ISupportInitialize)textBlock234).EndInit();
		((ISupportInitialize)border38).EndInit();
		Controls children159 = stackPanel58.Children;
		TextBlock textBlock236;
		TextBlock textBlock235 = (textBlock236 = new TextBlock());
		((ISupportInitialize)textBlock235).BeginInit();
		children159.Add(textBlock235);
		textBlock236.Text = "Chase fish 50% harder, and only pay 30% attention to obstacles. Bar moves faster toward fish with minimal dodging.";
		textBlock236.Classes.Add("banner-copy");
		textBlock236.TextWrapping = TextWrapping.Wrap;
		((ISupportInitialize)textBlock236).EndInit();
		((ISupportInitialize)stackPanel58).EndInit();
		Controls children160 = grid15.Children;
		StackPanel stackPanel60;
		StackPanel stackPanel59 = (stackPanel60 = new StackPanel());
		((ISupportInitialize)stackPanel59).BeginInit();
		children160.Add(stackPanel59);
		Grid.SetRow(stackPanel60, 4);
		Controls children161 = stackPanel60.Children;
		TextBlock textBlock238;
		TextBlock textBlock237 = (textBlock238 = new TextBlock());
		((ISupportInitialize)textBlock237).BeginInit();
		children161.Add(textBlock237);
		textBlock238.Text = "Full brake on overlap";
		textBlock238.Classes.Add("field-label");
		((ISupportInitialize)textBlock238).EndInit();
		Controls children162 = stackPanel60.Children;
		Border border40;
		Border border39 = (border40 = new Border());
		((ISupportInitialize)border39).BeginInit();
		children162.Add(border39);
		border40.Background = new ImmutableSolidColorBrush(404826688u);
		border40.CornerRadius = new CornerRadius(6.0, 6.0, 6.0, 6.0);
		border40.Padding = new Thickness(10.0, 6.0, 10.0, 6.0);
		TextBlock textBlock240;
		TextBlock textBlock239 = (textBlock240 = new TextBlock());
		((ISupportInitialize)textBlock239).BeginInit();
		border40.Child = textBlock239;
		textBlock240.Text = "if(abs(avoidance_error) > abs(pursuit_error) * 2, 0, (pursuit_error * pursuit_weight + avoidance_error * avoidance_weight) / max(pursuit_weight + avoidance_weight, 0.001))";
		textBlock240.FontFamily = new FontFamily(((IUriContext)context).BaseUri, "Consolas");
		textBlock240.FontSize = 13.0;
		((ISupportInitialize)textBlock240).EndInit();
		((ISupportInitialize)border40).EndInit();
		Controls children163 = stackPanel60.Children;
		TextBlock textBlock242;
		TextBlock textBlock241 = (textBlock242 = new TextBlock());
		((ISupportInitialize)textBlock241).BeginInit();
		children163.Add(textBlock241);
		textBlock242.Text = "If the avoid force is more than double the pursuit force (a danger is very close), freeze the bar (output 0 error). Otherwise use the normal weighted blend.";
		textBlock242.Classes.Add("banner-copy");
		textBlock242.TextWrapping = TextWrapping.Wrap;
		((ISupportInitialize)textBlock242).EndInit();
		((ISupportInitialize)stackPanel60).EndInit();
		((ISupportInitialize)grid15).EndInit();
		((ISupportInitialize)stackPanel50).EndInit();
		((ISupportInitialize)border30).EndInit();
		((ISupportInitialize)stackPanel30).EndInit();
		((ISupportInitialize)scrollViewer8).EndInit();
		((ISupportInitialize)grid2).EndInit();
		((ISupportInitialize)border2).EndInit();
		((ISupportInitialize)P_1).EndInit();
		if (P_1 is StyledElement styled)
		{
			NameScope.SetNameScope(styled, context.AvaloniaNameScope);
		}
		context.AvaloniaNameScope.Complete();
	}

	[CompilerGenerated]
	private static void _0021XamlIlPopulateTrampoline(HelpWindow P_0)
	{
		if (_0021XamlIlPopulateOverride != null)
		{
			_0021XamlIlPopulateOverride(P_0);
		}
		else
		{
			_0021XamlIlPopulate(XamlIlRuntimeHelpers.CreateRootServiceProviderV3(null), P_0);
		}
	}
}
