<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>PFMS</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <None Remove="-AvaloniaResources" />
    <EmbeddedResource Include="-AvaloniaResources" LogicalName="!AvaloniaResources" />
  </ItemGroup>
  <ItemGroup>
    <None Include="original-runtime\libSkiaSharp.dll" Link="libSkiaSharp.dll" CopyToOutputDirectory="PreserveNewest" />
    <None Include="original-runtime\libHarfBuzzSharp.dll" Link="libHarfBuzzSharp.dll" CopyToOutputDirectory="PreserveNewest" />
    <None Include="original-runtime\av_libglesv2.dll" Link="av_libglesv2.dll" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Avalonia.Controls">
      <HintPath>original-runtime\Avalonia.Controls.dll</HintPath>
    </Reference>
    <Reference Include="Avalonia.Base">
      <HintPath>original-runtime\Avalonia.Base.dll</HintPath>
    </Reference>
    <Reference Include="CommunityToolkit.Mvvm">
      <HintPath>original-runtime\CommunityToolkit.Mvvm.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.ML.OnnxRuntime">
      <HintPath>original-runtime\Microsoft.ML.OnnxRuntime.dll</HintPath>
    </Reference>
    <Reference Include="System.Drawing.Common">
      <HintPath>original-runtime\System.Drawing.Common.dll</HintPath>
    </Reference>
    <Reference Include="System.Private.Windows.Core">
      <HintPath>original-runtime\System.Private.Windows.Core.dll</HintPath>
    </Reference>
    <Reference Include="System.Private.Windows.GdiPlus">
      <HintPath>original-runtime\System.Private.Windows.GdiPlus.dll</HintPath>
    </Reference>
    <Reference Include="Avalonia.Markup.Xaml">
      <HintPath>original-runtime\Avalonia.Markup.Xaml.dll</HintPath>
    </Reference>
    <Reference Include="Avalonia.Desktop">
      <HintPath>original-runtime\Avalonia.Desktop.dll</HintPath>
    </Reference>
    <Reference Include="Avalonia.Fonts.Inter">
      <HintPath>original-runtime\Avalonia.Fonts.Inter.dll</HintPath>
    </Reference>
    <Reference Include="Avalonia.Themes.Fluent">
      <HintPath>original-runtime\Avalonia.Themes.Fluent.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
